### ISSUE TITLE
Serialization of an array of OpenType entities fails when OpenType entity contains a property of an array of complex type

### ISSUE THREAD

**Issue by garegina** [OData/AspNetCoreOData#1067]
**Assemblies affected**
Which assemblies and versions are known to be affected e.g. ASP.NET Core OData 8.x

```
Microsoft.AspNetCore.OData Version=8.2.3
```

**Describe the bug**

```
Serialization of an array of OpenType entities fails when OpenType entity contains a property of an array of complex type
```

**Reproduce steps**
The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.

Create an ASP.NET core odata project. Sharing the content of program.cs
```
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.OData;
using Microsoft.AspNetCore.OData.Query;
using Microsoft.AspNetCore.OData.Routing.Controllers;
using Microsoft.OData.Edm;
using Microsoft.OData.ModelBuilder;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace ReproOpenTypeSerializationIssue
{
    public class MyOpenTypeEntityController : ODataController
    {
        [EnableQuery]
        public async Task<ActionResult<IEnumerable<MyOpenTypeEntity>>> Get()
        {
            string json =
@"
[
    {
        ""id"": ""MyOpenTypeEntity 1"",
        ""ArrayProperty"": [
            {
                ""SubProperty1"": ""SubProperty1Value"",
                ""SubProperty2"": ""SubProperty2Value"",
                ""SubProperty3"": ""SubProperty3Value""
            }
        ]
    }
]
";

            MyOpenTypeEntity[] iksDynamicEntities = JsonConvert.DeserializeObject<MyOpenTypeEntity[]>(json);
            return Ok(iksDynamicEntities);
        }
    }

    public class MyOpenTypeEntity
    {
        [Key]
        public string id { get; set; }

        [Newtonsoft.Json.JsonExtensionData]
        public IDictionary<string, object> DynamicProperties { get; set; }
    }

    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);

            builder.Services.AddControllers().AddOData(
                options => options.Select().Filter().OrderBy().Expand().Count().SetMaxTop(null).AddRouteComponents(
                    "odata",
                    BuildODataEdmModel()));
            builder.Services.AddEndpointsApiExplorer();
            builder.Services.AddSwaggerGen();
            var app = builder.Build();
            app.UseSwagger();
            app.UseSwaggerUI();
            app.UseDeveloperExceptionPage();

            app.UseRouting();

            app.UseEndpoints(endpoints => endpoints.MapControllers());

            app.Run();
        }

        private static IEdmModel BuildODataEdmModel()
        {
            var modelBuilder = new ODataConventionModelBuilder();
            modelBuilder.Namespace = "ReproOpenTypeSerializationIssue";
            var entityTypeConfig = modelBuilder.EntityType<MyOpenTypeEntity>();
            modelBuilder.EntitySet<MyOpenTypeEntity>("MyOpenTypeEntity");

            return modelBuilder.GetEdmModel();
        }
    }
}
```

Also sharing the content of the .csproj
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OData" Version="8.2.3" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="7.0.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

</Project>

```

**Data Model**
Please share your Data model, for example, your C# class.

**EDM (CSDL) Model**
Please share your Edm model, for example, CSDL file.
You can send `$metadata` to get a CSDL XML content.

**Request/Response**
Please share your request Uri, head or the request body
Please share your response head, body.

Request
```
GET https://localhost:7192/odata/MyOpenTypeEntity
```

Response
```
no data is being sent
```

**Expected behavior**
```
200 OK with the entity array response
```

**Screenshots**
<img width="1248" alt="image" src="https://github.com/OData/AspNetCoreOData/assets/8712560/3150606a-2a4f-4334-972d-4d9f27484cf4">

**Additional context**
Please share your call stack or any error message

```
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      Microsoft.OData.ODataException: The depth limit for entries in nested expanded navigation links was reached. The number of nested expanded entries cannot exceed 100.
         at Microsoft.OData.ODataWriterCore.ThrowODataException(String errorMessage, ODataItem item)
         at Microsoft.OData.ODataWriterCore.IncreaseResourceDepth()
         at Microsoft.OData.ODataWriterCore.WriteStartResourceImplementationAsync(ODataResource resource)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteResourceAsync(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInlineAsync(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceItemAsync(Object resourceValue, IEdmTypeReference resourceType, IEdmTypeReference parentSetType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteUntypedResourceSetItemAsync(Object item, IEdmTypeReference parentSetType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSetItemAsync(Object item, IEdmStructuredTypeReference elementType, Boolean isUntypedCollection, IEdmTypeReference resourceSetType, ODataWriter writer, IODataEdmTypeSerializer resourceSerializer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSetAsync(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInlineAsync(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteDynamicComplexPropertyAsync(Object propertyValue, IEdmTypeReference edmType, ResourceContext resourceContext, ODataWriter writer)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteDynamicComplexPropertiesAsync(ResourceContext resourceContext, ODataWriter writer)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteResourceAsync(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInlineAsync(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceItemAsync(Object resourceValue, IEdmTypeReference resourceType, IEdmTypeReference parentSetType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteUntypedResourceSetItemAsync(Object item, IEdmTypeReference parentSetType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSetItemAsync(Object item, IEdmStructuredTypeReference elementType, Boolean isUntypedCollection, IEdmTypeReference resourceSetType, ODataWriter writer, IODataEdmTypeSerializer resourceSerializer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSetAsync(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInlineAsync(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteDynamicComplexPropertyAsync(Object propertyValue, IEdmTypeReference edmType, ResourceContext resourceContext, ODataWriter writer)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteDynamicComplexPropertiesAsync(ResourceContext resourceContext, ODataWriter writer)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteResourceAsync(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInlineAsync(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceItemAsync(Object resourceValue, IEdmTypeReference resourceType, IEdmTypeReference parentSetType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteUntypedResourceSetItemAsync(Object item, IEdmTypeReference parentSetType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSetItemAsync(Object item, IEdmStructuredTypeReference elementType, Boolean isUntypedCollection, IEdmTypeReference resourceSetType, ODataWriter writer, IODataEdmTypeSerializer resourceSerializer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSetAsync(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInlineAsync(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteDynamicComplexPropertyAsync(Object propertyValue, IEdmTypeReference edmType, ResourceContext resourceContext, ODataWriter writer)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteDynamicComplexPropertiesAsync(ResourceContext resourceContext, ODataWriter writer)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteResourceAsync(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
...
```

**Comment by gathogojr** [comment]
Thank you @garegina for reporting this issue.
Looking through the description of your issue, you mention that the "**OpenType entity contains a property of an array of complex type**".
What type is this object that you're stashing in your dictionary?
```csharp
{
     ""SubProperty1"": ""SubProperty1Value"",
     ""SubProperty2"": ""SubProperty2Value"",
     ""SubProperty3"": ""SubProperty3Value""
}
```
You say it's a complex type, but it's not represented in the Edm model.
The above JSON object is deserialized as a Newtonsoft `JObject` object so it's not a complex type in OData semantics.

If you initialize a `MyOpenTypeEntity` object and populate it with dynamic properties including complex objects and complex collections, you'll find that they'll be serialized without an issue. In your case, the array object in your JSON payload is being deserialized into an object that OData doesn't know how to serialize.

**Comment by garegina** [comment]
Is there a default open /dynamic type that data serializer can treat it as? We do not know in advance property names and types to register in EDM.

**Comment by gathogojr** [comment]
@garegina Do you receive JSON from an upstream service such that you have to first deserialize into an object using Newtonsoft.Json library before serializing the same object(s) using the OData serializer?

**Comment by gathogojr** [comment]
This would be a rare unsupported scenario. You could try the non-Edm approach that gives the query options capabilities but doesn't rely on OData serialization. https://devblogs.microsoft.com/odata/enabling-endpoint-routing-in-odata/#non-edm-approach

**Comment by garegina** [comment]
i agree maybe it is a rare scenario but I can see a use-cases for this. i found another issue which is still open, https://github.com/OData/AspNetCoreOData/issues/81, can you maybe evaluate it and see if it can be supported?
