### ISSUE TITLE
Select queries return an error on a dynamic property dictionary.

### ISSUE THREAD

**Issue by TARGAZ** [OData/AspNetCoreOData#1224]
Hello,

On a entity with a complex property that has dynamic property dictionary. I can't do a select clause on this complex property.

**Assemblies affected**
Microsoft.AspNetCore.OData 8.2.5

**Reproduce steps**
1.Clone the repository : https://github.com/TARGAZ/ODataSelectDynamicPropertyBug
2.Run
3.Try queries :
* https://localhost:7092/odata/customers
* https://localhost:7092/odata/customers?$select=id
* https://localhost:7092/odata/customers?$select=Name (throw error)
* https://localhost:7092/odata/customers?$select=Name/en (throw error)

**Expected result**
First query : https://localhost:7092/odata/customers?$select=Name
```json
{
  "@odata.context": "https://localhost:7092/odata/$metadata#Customers",
  "value": [
    {
      "Name": {
        "en": "english",
        "fr": "french"
      }
    },
    {
      "Name": {
        "en": "english",
        "fr": "french"
      }
    },
    {
      "Name": {
        "en": "english",
        "fr": "french"
      }
    }
  ]
}
```
Second Query : https://localhost:7092/odata/customers?$select=Name/en
```json
{
  "@odata.context": "https://localhost:7092/odata/$metadata#Customers",
  "value": [
    {
      "Name": {
        "en": "english"
      }
    },
    {
      "Name": {
        "en": "english"
      }
    },
    {
      "Name": {
        "en": "english"
      }
    }
  ]
}
```

**Actual result**
The error is the same for both queries :
```
The query specified in the URI is not valid. The given model does not contain the type 'System.Collections.Generic.KeyValuePair`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]'.
```

Stack trace :
```
at Microsoft.AspNetCore.OData.Query.Expressions.QueryBinderContext..ctor(QueryBinderContext context, ODataQuerySettings querySettings, Type clrType)
at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.ProjectAsWrapper(QueryBinderContext context, Expression source, SelectExpandClause selectExpandClause, IEdmStructuredType structuredType, IEdmNavigationSource navigationSource, OrderByClause orderByClause, ComputeClause computeClause, Nullable`1 topOption, Nullable`1 skipOption, Nullable`1 modelBoundPageSize)
at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.BuildSelectedProperty(QueryBinderContext context, Expression source, IEdmStructuredType structuredType, IEdmStructuralProperty structuralProperty, PathSelectItem pathSelectItem, IList`1 includedProperties)
at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.BuildPropertyContainer(QueryBinderContext context, Expression source, IEdmStructuredType structuredType, IDictionary`2 propertiesToExpand, IDictionary`2 propertiesToInclude, IList`1 computedProperties, ISet`1 autoSelectedProperties, Boolean isSelectingOpenTypeSegments, Boolean isSelectedAll)
at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.ProjectElement(QueryBinderContext context, Expression source, SelectExpandClause selectExpandClause, IEdmStructuredType structuredType, IEdmNavigationSource navigationSource)
at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.BindSelectExpand(SelectExpandClause selectExpandClause, QueryBinderContext context)
at Microsoft.AspNetCore.OData.Query.Expressions.BinderExtensions.ApplyBind(ISelectExpandBinder binder, IQueryable source, SelectExpandClause selectExpandClause, QueryBinderContext context)
at Microsoft.AspNetCore.OData.Query.SelectExpandQueryOption.ApplyTo(IQueryable queryable, ODataQuerySettings settings)
at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplySelectExpand[T](T entity, ODataQuerySettings querySettings)
at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
```

**Comment by julealgon** [comment]
Based on your code..... can you check whether replacing `IDictionary` on the `ExtendedProperties` property with `Dictionary` (the concrete class) makes a difference here?

```csharp
        public Dictionary<string, object> ExtendedProperties
```

IIRC, OData's EDM builder won't automatically match interfaces to implementations when they are found in the model. You either need to specify the type explicitly in that case, or just type it to the concrete type and it will be picked up automatically.

Let us know if that changes the error in any way.

**Comment by xuzhg** [comment]
@TARGAZ OData needs the 'model type' as POCO class, so your 'LocalizableString' can't be treated correctly since it's derived from 'ReadOnlyDictionary< >'.

If you replace your 'LocalizableString' definition using composition, not using inheritance, it should work:

```C#
public sealed class LocalizableString/* : ReadOnlyDictionary<string, string>*/
{
    private IDictionary<string, object> _values;
    ......
}
```

![image](https://github.com/OData/AspNetCoreOData/assets/9426627/759bbd3e-88e3-47ec-b634-10c8eed34ece)

**Comment by TARGAZ** [comment]
Hello,
Thank you for your help. It works really well :).
