### ISSUE TITLE
ODataException when entity has DateOnly or TimeOnly member

### ISSUE THREAD

**Issue by andygjp** [OData/AspNetCoreOData#1294]
**Assemblies affected**
Microsoft.AspNetCore.OData 9.0.0-rc.1
Microsoft.OData.Core 8.0.0-rc.1

**Describe the bug**
Cannot GET or POST entities that contain DateOnly and TimeOnly types after upgrading to v9 rc1

**Error**

Here is the error stacktrace:

```
An unhandled exception has occurred while executing the request.
      Microsoft.OData.ODataException: An ODataPrimitiveValue was instantiated with a value of type 'System.DateOnly'. ODataPrimitiveValue can only wrap values which can be represented as primitive EDM types.
         at Microsoft.OData.ODataPrimitiveValue..ctor(Object value)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataPrimitiveSerializer.CreatePrimitive(Object value, IEdmPrimitiveTypeReference primitiveType, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataPrimitiveSerializer.CreateODataPrimitiveValue(Object graph, IEdmPrimitiveTypeReference primitiveType, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataPrimitiveSerializer.CreateODataValue(Object graph, IEdmTypeReference expectedType, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataSerializerPropertyHelper.CreateProperty(IODataEdmTypeSerializer serializer, Object graph, IEdmTypeReference expectedType, String elementName, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.CreateStructuralProperty(IEdmStructuralProperty structuralProperty, ResourceContext resourceContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.CreateStructuralPropertyBag(SelectExpandNode selectExpandNode, ResourceContext resourceContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.CreateResource(SelectExpandNode selectExpandNode, ResourceContext resourceContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteResourceAsync(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInlineAsync(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSetItemAsync(Object item, IEdmStructuredTypeReference elementType, Boolean isUntypedCollection, IEdmTypeReference resourceSetType, ODataWriter writer, IODataEdmTypeSerializer resourceSerializer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSetAsync(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInlineAsync(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectAsync(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)
         at Microsoft.AspNetCore.OData.Formatter.ODataOutputFormatterHelper.WriteToStreamAsync(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, HttpRequest request, IHeaderDictionary requestHeaders, IODataSerializerProvider serializerProvider)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Reproduce steps**
I've created a sample repo: https://github.com/andygjp/DateOnlySerializationError

**Expected behavior**
I should be able to GET and POST entities that have DateOnly and TimeOnly types

**Comment by julealgon** [comment]
Duplicate:
- https://github.com/OData/AspNetCoreOData/issues/545

**Comment by andygjp** [comment]
I don't think they are quite the same.

Serialization of DateOnly members has been working for me using Microsoft.AspNetCore.OData 8.2.5.

I've included an image of the response I get when I query my test environment:

![image](https://github.com/user-attachments/assets/1fafddec-3d01-4f3c-9a40-a1223f4b1a91)

And an image of the response I receive when I get (minus the `$select`) my test environment:

![image](https://github.com/user-attachments/assets/47e59cd7-f13e-4658-9489-caee1d56cdf1)

When I upgrade my development environment to 9 rc1 and execute the same requests, I get:

![image](https://github.com/user-attachments/assets/d53cb352-5e9a-4af1-b45f-5069d9eb429f)

And:

![image](https://github.com/user-attachments/assets/6852fa0a-fd34-4610-a16a-032c2faf3809)

I think the error might be related to this piece of code in `Microsoft.AspNetCore.OData.Edm.EdmPrimitiveHelper.ConvertPrimitiveValue`:

![image](https://github.com/user-attachments/assets/87de05dc-4ba3-48a6-ae30-92648d326a57)

Changing `#if NET6_0` to `#if NET6_0_OR_GREATER` might fix it:

![image](https://github.com/user-attachments/assets/3ede6b27-f495-4fb4-bbdc-1d7072e0a13d)

There are many places that check `#if NET6_0`, they should probably be checked too:

![image](https://github.com/user-attachments/assets/6d1f3306-63b2-4ead-90ad-6e2abc16535b)

**Comment by andygjp** [comment]
If I change my sample project to reference my fork of AspNetCoreOData, with all instances of `#if NET6_0` on the `dev-9.x` branch changed to `#if NET6_0_OR_GREATER`:

![image](https://github.com/user-attachments/assets/840001f9-0cff-4ada-af16-08800b0a3e6e)

Then the requests work as expected:

![image](https://github.com/user-attachments/assets/7f767876-25b1-4bcc-85a9-b5c5fbb787b8)

**Comment by andygjp** [comment]
Or merge my PR: https://github.com/OData/AspNetCoreOData/pull/1296

**Comment by MichalWeczorek** [comment]
i vote for fixing this problem and Full Support of DateOnly and TimeOnly

**Comment by andygjp** [comment]
The PR was merged and I can confirm that my issue has been resolved.
