### ISSUE TITLE
Dto conversion issue

### ISSUE THREAD

**Issue by mkalinski93** [OData/AspNetCoreOData#146]
Hello,

I want to return an IQueryable<FakeProductDto> to the client but all I get is 'System.ArgumentException'
We need to be able to query raw entites but sending back dto´s.

My current configuration looks like this 

FakeProduct EntitySet
```csharp
public void Apply(ODataModelBuilder builder, ApiVersion apiVersion, string? routePrefix) {
    EntitySetConfiguration<FakeProduct> fakeProductDto = builder.EntitySet<FakeProduct>("Test");
    fakeProductDto.EntityType.HasKey(x => x.ItemCode);
}
```

FakeProductDto EntityType
```csharp
public void Apply(ODataModelBuilder builder, ApiVersion apiVersion, string? routePrefix) {
    builder.EntityType<FakeProductDto>().HasKey(x => x.ItemCode);
}
```
Startup
```csharp
services.AddApiVersioning(options => {
    options.ReportApiVersions = true;
    options.AssumeDefaultVersionWhenUnspecified = true;
    options.DefaultApiVersion = new ApiVersion(1, 0);
});
services.AddOData().EnableApiVersioning();

app.UseEndpoints(endpoints => {
    endpoints.MapHangfireDashboard();
    endpoints.MapVersionedODataRoute("api", "api/v{version:apiVersion}", modelBuilder.GetEdmModels())
        .Filter().OrderBy().SkipToken().MaxTop(100).Count().Select().Expand().EnableDependencyInjection();
});
```

TestController
```csharp
[EnableQuery]
[HttpGet("GetQueryItems")]
public IQueryable<FakeProductDto> Get(ODataQueryOptions<FakeProductDto> product) {
    
    var products = GetProjectionResult<FakeProduct, FakeProductDto, FakeProductDto>(_testData.Products.AsQueryable());
    return products;
}
```
`*GetProjectionResult is actually a helper to not have ODataqueryOptions been placed in the controllers parameters list due to the reason that Swagger is resolving OdataQueryOption as a required body parameter`

Result 
`System.ArgumentException: Object of type 'System.Linq.EnumerableQuery`1[Pricing.Api.Abstractions.Contracts.V1.DTO.FakeProductDto]' cannot be converted to type 'System.Linq.IQueryable`1[Pricing.Shared.Providers.FakeProduct]'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.AspNet.OData.ExpressionHelpers.OrderBy(IQueryable query, LambdaExpression orderByLambda, OrderByDirection direction, Type type, Boolean alreadyOrdered)
   at Microsoft.AspNet.OData.Query.OrderByQueryOption.AddOrderByQueryForProperty(IQueryable query, ODataQuerySettings querySettings, OrderByClause orderbyClause, IQueryable querySoFar, OrderByDirection direction, Boolean alreadyOrdered)
   at Microsoft.AspNet.OData.Query.OrderByQueryOption.ApplyToCore(IQueryable query, ODataQuerySettings querySettings)
   at Microsoft.AspNet.OData.Query.OrderByQueryOption.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at Microsoft.AspNet.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at Microsoft.AspNet.OData.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
   at Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func`2 modelFunction, IWebApiRequestMessage request, Func`2 createQueryOptionFunction)
   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func`2 modelFunction, Func`2 createQueryOptionFunction, Action`1 createResponseAction, Action`3 createErrorAction)
   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext)
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

We try to have the ability to let the client use the entity as a queryfilter and load just demanded data from the datastore which then gets projected to the dto type.

I was doing fine when FakeDataDto was an EdmSet, but we are planning to have different dto types for the result, so we would not be able to just use the FakeDataDto as an EdmSet.

Am I missing something?

Feel free to let me know if you need further information.

**Comment by mkalinski93** [comment]
We came up with the solution to not use dto objects.
