### ISSUE TITLE
Accessing ODataQueryOptions in GET on single entity requires to return IEnumerable<T>

### ISSUE THREAD

**Issue by richardrobberse** [OData/AspNetCoreOData#149]
## Problem description
Whenever you add `ODataQueryOptions` as a parameter it forces the controller's method to return an IEnumerable<T> response.
This is fine when you query on an entity set, but when you simply want to expand properties of a single entity this becomes an issue.
We're using the ODataQueryOptions to figure out which properties to expand, we pass those options to AutoMapper's ProjectTo method to ensure we're not expanding properties (and reading data) we're not interested in.

## Repro using the sample application
1. Add `ODataQueryOptions` as a parameter:
./sample/ODataRoutingSample/Controllers/ProductsController.cs
```C#
[EnableQuery]
[HttpGet]
public IActionResult Get(int key, ODataQueryOptions options)
{
    var product = _context.Products.FirstOrDefault(p => p.Id == key);
    if (product == null)
    {
        return NotFound($"Not found product with id = {key}");
    }

    return Ok(product);
}
```
2. Query the endpoint: http://localhost:5000/products(1)?$expand=detail
3. Exception regarding IEnumerable<T> will be thrown

## Version
Microsoft.AspNetCore.OData" Version="8.0.0-rc

**Comment by xuzhg** [comment]
@richardrobberse What's the error message?

**Comment by richardrobberse** [comment]
@xuzhg Will share it asap!

**Comment by richardrobberse** [comment]
@xuzhg here's the exception and the project.
[ODataRoutingSampleRepro.zip](https://github.com/OData/AspNetCoreOData/files/6378992/ODataRoutingSampleRepro.zip)

`
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Cannot create an EDM model as the action 'Get' on controller 'Products' has a return type 'Microsoft.AspNetCore.Mvc.IActionResult' that does not implement IEnumerable<T>.
         at Microsoft.AspNetCore.OData.Query.ODataQueryParameterBindingAttribute.ODataQueryParameterBinding.GetEntityClrTypeFromActionReturnType(ActionDescriptor actionDescriptor) in /Users/richardr/db/examples/AspNetCoreOData/src/Microsoft.AspNetCore.OData/Query/ODataQueryParameterBindingAttribute.cs:line 168
         at Microsoft.AspNetCore.OData.Query.ODataQueryParameterBindingAttribute.ODataQueryParameterBinding.BindModelAsync(ModelBindingContext bindingContext) in /Users/richardr/db/examples/AspNetCoreOData/src/Microsoft.AspNetCore.OData/Query/ODataQueryParameterBindingAttribute.cs:line 95
         at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinder.BindModelAsync(ModelBindingContext bindingContext)
         at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.OData.Batch.ODataBatchMiddleware.Invoke(HttpContext context) in /Users/richardr/db/examples/AspNetCoreOData/src/Microsoft.AspNetCore.OData/Batch/ODataBatchMiddleware.cs:line 66
         at Microsoft.AspNetCore.OData.Query.ODataQueryRequestMiddleware.Invoke(HttpContext context) in /Users/richardr/db/examples/AspNetCoreOData/src/Microsoft.AspNetCore.OData/Query/ODataQueryRequestMiddleware.cs:line 64
         at Microsoft.AspNetCore.OData.Routing.ODataRouteDebugMiddleware.Invoke(HttpContext context) in /Users/richardr/db/examples/AspNetCoreOData/src/Microsoft.AspNetCore.OData/Routing/ODataRouteDebugMiddleware.cs:line 82
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
`

**Comment by xuzhg** [comment]
@richardrobberse The error message gives you the hint that we can't create the model from `IActionResult`, because there's no "CLR" type. Beside, you use "ODataQueryOptions" as the parameter type. There's no "CLR" type associated.
You should use "ODataQueryOptions< T >" to define the parameter type.

**Comment by richardrobberse** [comment]
@xuzhg Thanks a lot, got it to work now ;)
I think it could be a valuable addition to the samples!
