### ISSUE TITLE
Dynamic model fails with EnableQuery and filtering.

### ISSUE THREAD

**Issue by hvidgaard-ims** [OData/AspNetCoreOData#173]
I'm implementing an OData api for a backend with dynamic model. The backend has one or more types with only one common property, an Id. The rest is defined by configuration and I would like to present those configuration changes without having to create new versions of the api. I have managed to create and reflect the EdmModel dynamically, but when I try to use a filter I get an exception using a dictionary for dynamic properties.

I have attached a project that reproduces the problem.

[ODataDynamic2.zip](https://github.com/OData/AspNetCoreOData/files/6509325/ODataDynamic2.zip)

When I create a request to "http://localhost:28038/v1/CustomType1s?$filter=Title eq 'Test1'" I get the following error

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindPropertyAccessExpression(SingleValueOpenPropertyAccessNode openNode, PropertyInfo prop)
   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindDynamicPropertyAccessQueryNode(SingleValueOpenPropertyAccessNode openNode)
   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindSingleValueNode(SingleValueNode node)
   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)
   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindConvertNode(ConvertNode convertNode)
   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindSingleValueNode(SingleValueNode node)
   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)
   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindBinaryOperatorNode(BinaryOperatorNode binaryOperatorNode)
   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindSingleValueNode(SingleValueNode node)
   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.Bind(QueryNode node)
   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindExpression(SingleValueNode expression, RangeVariable rangeVariable, Type elementType)
   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.BindFilterClause(FilterBinder binder, FilterClause filterClause, Type filterType)
   at Microsoft.AspNetCore.OData.Query.Expressions.FilterBinder.Bind(IQueryable baseQuery, FilterClause filterClause, Type filterType, ODataQueryContext context, ODataQuerySettings querySettings)
   at Microsoft.AspNetCore.OData.Query.FilterQueryOption.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext)
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Am I missing something crucial or should it be done in a different way if it's even possible?

**Comment by xuzhg** [comment]
@hvidgaard-ims I don't know why do you want to do like this.

Because your model built in startup.cs is not used to do query.

But with the following code changes (using the latest nightly), it should work:

```C#
public class ODataDynamicController : ODataController
{
      // add following method
       private static IEdmModel GetEdmModel()
        {
            var builder = new ODataConventionModelBuilder();
            builder.EntitySet<DynamicModel>("models");
            return builder.GetEdmModel();
        }

        [EnableQuery]
        public ActionResult<IQueryable> Get(CancellationToken token)
        {
            
            if (!this.RouteData.Values.ContainsKey("TemplateSetName"))
            {
                throw new InvalidOperationException("Case Template Route unknown");
            }
             // Add following codes
            IEdmModel model = GetEdmModel();
            Request.ODataFeature().Model = model;

            IEdmEntitySet entitySet = model.FindDeclaredEntitySet("models");
            Request.ODataFeature().Path = new Microsoft.OData.UriParser.ODataPath(new EntitySetSegment(entitySet));
           
          ....
}
```

And change (breaking changes in latest nightly)

```C#
    internal class EntitySetTemplateSegment : ODataSegmentTemplate
    {
        private readonly string entitySetName;
        private readonly IEdmType edmModel1;
        public EntitySetTemplateSegment(string entitySetName, IEdmType edmModel)
        {
            this.entitySetName = entitySetName;
            this.edmModel1 = edmModel;
        }

        public override IEnumerable<string> GetTemplates(ODataRouteOptions options)
        {
            yield return $"/{this.entitySetName}";
        }

        public override bool TryTranslate(ODataTemplateTranslateContext context)
        {
            // if you want to support case-insenstivie
            var sets = context.Model.EntityContainer.EntitySets();
            var edmEntitySet = sets
                .FirstOrDefault(e => string.Equals(this.entitySetName, e.Name, StringComparison.OrdinalIgnoreCase));

            if (edmEntitySet != null)
            {
                context.Segments.Add(new EntitySetSegment(edmEntitySet));
                context.RouteValues.Add("TemplateSetName", this.entitySetName);
                return true;
            }

            return false;
        }
    }
```

It can work:
![image](https://user-images.githubusercontent.com/9426627/119085093-e1993500-b9b7-11eb-8c1a-5cff04df47c4.png)

**Comment by hvidgaard-ims** [comment]
What I am trying to do is have the model reflect the configuration in the backend. I already have an iQueryable I can use so it seemed like a good solution rather than trying to parse the query expressions manually. Is there another way to do this? Ideally it can reevaluate the model every x minutes.
