### ISSUE TITLE
Microsoft.OData.ODataException when returning a SingleResult from a function

### ISSUE THREAD

**Issue by papillon** [OData/AspNetCoreOData#18]
Here is an issue that seems to occur in the current version `8.0.0-preview` (and also in the current master branch). It worked correctly in version `7.5.1`.

I have a controller method that returns an single entity `IQueryable<User>`, because I would like to use it with expand:
```
[EnableQuery]
[HttpGet("current")]
public ActionResult<SingleResult<User>> Current()
{
    var currentUser = dbContext.Users().Where(u => u.Id == _currentUser.Id);
    return Ok(SingleResult.Create(currentUser));
}
```
It's defined in the EdmModel like this:
``` 
builder.EntityType<User>().Collection
    .Function("Current")
    .Returns<User>();
```

This throws an `ODataException` during serialization:

> When writing a JSON response, a user model must be specified and the entity set and entity type must be passed to the ODataMessageWriter.CreateODataResourceWriter method or the ODataResourceSerializationInfo must be set on the ODataResource or ODataResourceSet that is being written.

```
Stacktrace:
   at Microsoft.OData.ODataResourceTypeContext.ValidateAndReturn[T](T value)
   at Microsoft.OData.ODataResourceTypeContext.get_NavigationSourceName()
   at Microsoft.OData.ODataContextUrlInfo.Create(ODataResourceTypeContext typeContext, ODataVersion version, Boolean isSingle, ODataUri odataUri)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceSerializer.<>c__DisplayClass11_0.<WriteResourceContextUri>b__0()
   at Microsoft.OData.JsonLight.ODataJsonLightSerializer.WriteContextUriProperty(ODataPayloadKind payloadKind, Func`1 contextUrlInfoGen, ODataContextUrlInfo parentContextUrlInfo, String propertyName)
   at Microsoft.OData.JsonLight.ODataJsonLightResourceSerializer.WriteResourceContextUri(ODataResourceTypeContext typeContext, ODataContextUrlInfo parentContextUrlInfo)
   at Microsoft.OData.JsonLight.ODataJsonLightWriter.StartResource(ODataResource resource)
   at Microsoft.OData.ODataWriterCore.<>c__DisplayClass121_0.<WriteStartResourceImplementation>b__0()
   at Microsoft.OData.ODataWriterCore.InterceptException(Action action)
   at Microsoft.OData.ODataWriterCore.WriteStartResourceImplementation(ODataResource resource)
   at Microsoft.OData.ODataWriterCore.WriteStart(ODataResource resource)
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType) in C:\Users\stieger\Documents\Projects\DYCE\Backend\Playground\AspNetCoreOData\src\Microsoft.AspNetCore.OData\Formatter\Serialization\ODataResourceSerializer.cs:line 362
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext) in C:\Users\stieger\Documents\Projects\DYCE\Backend\Playground\AspNetCoreOData\src\Microsoft.AspNetCore.OData\Formatter\Serialization\ODataResourceSerializer.cs:line 85
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext) in C:\Users\stieger\Documents\Projects\DYCE\Backend\Playground\AspNetCoreOData\src\Microsoft.AspNetCore.OData\Formatter\Serialization\ODataResourceSerializer.cs:line 62
   at Microsoft.AspNetCore.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, HttpRequest request, IHeaderDictionary requestHeaders, ODataSerializerProvider serializerProvider) in C:\Users\stieger\Documents\Projects\DYCE\Backend\Playground\AspNetCoreOData\src\Microsoft.AspNetCore.OData\Formatter\ODataOutputFormatterHelper.cs:line 153
   at Microsoft.AspNetCore.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding) in C:\Users\stieger\Documents\Projects\DYCE\Backend\Playground\AspNetCoreOData\src\Microsoft.AspNetCore.OData\Formatter\ODataOutputFormatter.cs:line 230
```

Notes:
1) It works fine if I return the same result from a normal controller method without a special definition in the EdmModel, so SingleResult itself is not the problem:
```
[EnableQuery]
[HttpGet("{key}")]
public ActionResult<SingleResult<User>> Get(Guid key)
{
    var currentUser = dbContext.Users().Where(u => u.Id == _currentUser.Id);
    return Ok(SingleResult.Create(currentUser));
}
```
2) The exception also occurs when I rewrite the method like this:
```
[EnableQuery]
[HttpGet("current")]
public IActionResult Current()
{
    var currentUser = _userService.Users().Where(u => u.Id == _currentUser.Id).Single();
    return Ok(currentUser);
}
```
3) However it suddenly works if I remove the Single() call from the query:
```
    var currentUser = _userService.Users().Where(u => u.Id == _currentUser.Id);
```
4) Defining the function like this also does not work. This was the previous definition that worked in 7.5.1:
```
builder.EntityType<User>().Collection
    .Function("Current")
    .ReturnsFromEntitySet<User>("Users");
```

So the combination of SingleResult with the function definition seems to be the reason for this Exception. Is this a bug or am I doing something wrong?

**Comment by xuzhg** [comment]
@papillon If it's working 7.*, it must be a bug. Let me mark it as "bug" first, I will be back to do more investigation.

**Comment by ra-design** [comment]
I'm having the same issue - is there any news on this?

**Comment by RobTF** [comment]
I get the same;

Function definiton in EDM;
```
            var getConfigsByGroup =
                builder.EntitySet<WellbeingConfig>("Configs")
                .EntityType
                .Collection
                .Function("GetByGroup")
                .ReturnsFromEntitySet<WellbeingConfig>("Configs");
            getConfigsByGroup.Parameter<Guid>("GroupId").Required();
```

and controller method;
```
        [ODataRoute("Configs/GetByAccount(accountId={accountId})")]
        public async Task<IActionResult> GetByAccount(Guid accountId)
        {
             // code omitted
        }
```

**Comment by ra-design** [comment]
Just to share my investigation, don't know if it's helpful in any way:

I could reproduce this bug in the ODataRoutingSample by adding:
```
[HttpGet]
public IActionResult GetPerson()
{
    var p = new Person {FirstName = "Max", LastName = "TheSingle"};
    return Ok(p);
}

[HttpGet]
public IActionResult GetPeople()
{
    var people = new List<Person>()
    {
        new Person { FirstName = "Max", LastName = "TheFirst" },
        new Person { FirstName = "Max", LastName = "TheLast" }
    };
    return Ok(people);
}
```
to the ProductsController and
```
builder.EntityType<Product>().Collection.Function("GetPerson").ReturnsFromEntitySet<Person>("People");
builder.EntityType<Product>().Collection.Function("GetPeople").ReturnsCollectionFromEntitySet<Person>("People");
```
to EdmModelBuilder's `GetEdmModel()`.

As described by @papillon and @RobTF, the result is an ODataException in `ODataResourceTypeContext`, and from the exception message I think that in the method `ODataWriterCore.GetResourceSerializationInfo(...)`  (https://github.com/OData/odata.net/blob/cc8ba0890123c62bb9a99269553520ff0359a484/src/Microsoft.OData.Core/ODataWriterCore.cs#L1123)
either the `resource.SerializationInfo` (L1126) should be set or `this.CurrentScope.Item` (L1135) should not be null but hold the value of the resource's resource set.

Unfortunately my limited skills seem to be exhausted at this point, I can't find the place where to set this right or how to get a workaround (other than setting all return values to IEnumerable instead of single entities)

**Comment by davidyee** [comment]
What seems to work in my project is using the nightly build (any version starting from 8.0.0-Nightly202102050832 appears to work) and returning `SingleResult` instead of the generic `SingleResult<T>` in my OData controller. 

The recently released beta version and 8.0.0-Nightly202102041313 (Feb. 4) appears to return with the following exception:

System.Text.Json.JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles.

**Comment by richardrobberse** [comment]
Having the exact same issue, any workarounds? It's kind of blocking me :<
I guess downgrading to 7.* would cause a lot of other issues since I started this project on v8.

**Comment by PeterThornton4Ing** [comment]
Any news on this?
