### ISSUE TITLE
Unable to cast object of type 'Microsoft.OData.Edm.EdmUnknownEntitySet' to type 'Microsoft.OData.Edm.IEdmEntitySet'

### ISSUE THREAD

**Issue by aletc1** [OData/AspNetCoreOData#182]
I have a custom OData model backed by Entity Framework Core, and when executing a query like ```/Accounts?$top=1&$expand=Country``` with Accept ```application/json;odata.metadata=full``` the following exception raises:
```
System.InvalidCastException: Unable to cast object of type 'Microsoft.OData.Edm.EdmUnknownEntitySet' to type 'Microsoft.OData.Edm.IEdmEntitySet'.
         at Microsoft.AspNet.OData.Builder.LinkGenerationHelpers.GenerateBaseODataPathSegmentsForNonSingletons(ODataPath path, IEdmNavigationSource navigationSource, IList`1 odataPath)
         at Microsoft.AspNet.OData.Builder.LinkGenerationHelpers.GenerateBaseODataPathSegmentsForEntity(ResourceContext resourceContext, IList`1 odataPath)
         at Microsoft.AspNet.OData.Builder.LinkGenerationHelpers.GenerateBaseODataPathSegments(ResourceContext resourceContext)
         at Microsoft.AspNet.OData.Builder.LinkGenerationHelpers.GenerateSelfLink(ResourceContext resourceContext, Boolean includeCast)
         at Microsoft.AspNet.OData.Builder.NavigationSourceLinkBuilderAnnotation.<>c__DisplayClass5_0.<.ctor>b__0(ResourceContext resourceContext)
         at Microsoft.AspNet.OData.Builder.NavigationSourceLinkBuilderAnnotation.BuildIdLink(ResourceContext instanceContext, ODataMetadataLevel metadataLevel)
         at Microsoft.AspNet.OData.Builder.NavigationSourceLinkBuilderAnnotation.BuildEntitySelfLinks(ResourceContext instanceContext, ODataMetadataLevel metadataLevel)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateResource(SelectExpandNode selectExpandNode, ResourceContext resourceContext)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteComplexAndExpandedNavigationProperty(IEdmProperty edmProperty, SelectItem selectItem, ResourceContext resourceContext, ODataWriter writer)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteExpandedNavigationProperties(SelectExpandNode selectExpandNode, ResourceContext resourceContext, ODataWriter writer)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteResource(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSet(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInline(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
         at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObject(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)
         at Microsoft.AspNet.OData.Formatter.ODataOutputFormatterHelper.WriteToStream(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, IWebApiUrlHelper internaUrlHelper, IWebApiRequestMessage internalRequest, IWebApiHeaders internalRequestHeaders, Func`2 getODataMessageWrapper, Func`2 getEdmTypeSerializer, Func`2 getODataPayloadSerializer, Func`1 getODataSerializerContext)
         at Microsoft.AspNet.OData.Formatter.ODataOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|21_0(ResourceInvoker invoker, IActionResult result)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
```
This only happens if *odata.metadata=full* and *$expand* is used. If odata.metadata is not specified in the accept header, the query returns proper expanded data.

What could be the issue? EdmUnknownEntitySet shouldnt inherit from IEdmEntitySet?

## Version information

Applies to 8.x and 7.x of Microsoft.AspNetCore.OData. Running under .NET 5.

**Comment by aletc1** [comment]
**UPDATE**: I found the "why" of the exception, and the cause was that the EntitySet of my model did not have a NavigationPropertyBinding. When generating the IEdmModel, I just missed the entitySet.AddNavigationTarget(...) method to add the NavigationPropertyBinding.

Nevertheless, I think might be a bug, because if you cannot generate the proper link in the metadata, you should either omit the field (might violate the OData specification) or create better error message in order to inform that the metadata builder cannot find a path to generate the link.

**Comment by gathogojr** [comment]
Similar to https://github.com/OData/AspNetCoreOData/issues/412
