### ISSUE TITLE
Documentation on implementing NoGroupByAggregationWrapper in $apply

### ISSUE THREAD

**Issue by komdil** [OData/AspNetCoreOData#183]
I have a specific querable class that implements IQuerable. I am getting error on executing $apply query:

 System.NotSupportedException
  HResult=0x80131515
  Message=The expression 'new NoGroupByAggregationWrapper() {Container = new LastInChain() {Name = "TotalSum", Value = Convert({from Order $it in Convert([$it], IEnumerable`1) select [$it].Balance=> Sum()}, Object)}}' (type: System.Linq.Expressions.MemberInitExpression) is not supported by this LINQ provider.
  Source=Remotion.Linq
  StackTrace:
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.VisitUnhandledItem[TItem,TResult](TItem unhandledItem, String visitMethod, Func`2 baseBehavior)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.VisitMemberInit(MemberInitExpression expression)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)

I want to know how to implement NoGroupByAggregationWrapper in my linq query provider

**Comment by komdil** [comment]
Any suggestion here?

**Comment by MirolimMajidov** [comment]
Is there any updates/comments?
