### ISSUE TITLE
NullReferenceException: Value cannot be null. (Parameter 'edmModel')

### ISSUE THREAD

**Issue by weitzhandler** [OData/AspNetCoreOData#21]
Hi,

When trying to access an `OData` controller action I get this exception:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'edmModel')
    at Microsoft.AspNetCore.OData.Edm.EdmClrTypeMapExtensions.GetEdmType(IEdmModel edmModel, Type clrType)
    at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.GetModel(Type elementClrType, HttpRequest request, ActionDescriptor actionDescriptor)
    at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.GetODataQueryContext(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
    at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.GetModelBoundPageSize(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
    at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
    at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext)
    at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
    at MyProject.Services.SubdomainTenantInitializerMiddleware.Invoke(HttpContext context, ITenantProvider tenantProvider, ITenantOrchestrationService tenantOrchestrationService) in D:\Users\Shimmy\Source\Repos\MyProject\MyProject.Api\Services\SubdomainTenantInitializerMiddleware.cs:line 35
    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

Here's my setup:

```c#
void ConfigureOData(IServiceCollection services)
{
  services.AddTransient<EdmModelBuilder>();
  services.AddTransient(serviceProvider =>
    serviceProvider.GetRequiredService<EdmModelBuilder>().GetEdmModel());

  services
    .AddOptions<ODataOptions>()
    .Configure<IEdmModel>((odataOptions, edmModel) =>
    {
      Debug.Assert(edmModel != null);

      odataOptions
      .SetAttributeRouting(true)
      .Select()
      .Expand()
      .Filter()
      .OrderBy()
      .SetMaxTop(128)
      .Count()
      .AddModel(edmModel);
    });

  services.AddOData();
}
```

![image](https://user-images.githubusercontent.com/2716316/97639874-840bbe00-1a50-11eb-843e-c5cac0842aa5.png)

**Comment by xuzhg** [comment]
@weitzhandler Would you please share your repo?

**Comment by weitzhandler** [comment]
Sorry for my delay: https://github.com/weitzhandler/ODataRepro.

**Comment by xuzhg** [comment]
@weitzhandler Sorry for delay. 

the problem is that
1) The routing is directed to ASP.NET Core attribute routing, not OData routing.
2) So, it's back to the no-Edm scenario, and try to find the model on the request, but there's no model assigned.

If you change the following:

1)  Change your "EdmModelBuilder" as below:

```
public class EdmModelBuilder
    {
        public IEdmModel GetEdmModel()
        {
            var builder = new ODataConventionModelBuilder();
            builder.EntitySet<Entity>("Entities");
            return builder.GetEdmModel();
        }
    }
```

2) Remove the attributes on the "EntitiesController"

//[ApiController]
    //[Route("api/[controller]")]
    //[ApiExplorerSettings(IgnoreApi = true)]

3) Send request to:   `api/Entities` should work.

**Comment by weitzhandler** [comment]
So it's either an OData endpoint or a Web API one but not both?
