### ISSUE TITLE
Swagger not working

### ISSUE THREAD

**Issue by twmillett** [OData/AspNetCoreOData#214]
I'm trying to upgrade our project to .net core 5, which apparently requires upgrading to OData 8.  

But, OData 8 appears to be incompatible with [Microsoft.AspNetCore.OData.Versioning.ApiExplorer](https://github.com/microsoft/aspnet-api-versioning/issues/677), so I was required to remove the dependency on that and change the startup call to

```
 services.AddODataApiExplorer()
```

to instead use the one in `Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer`

```
 services.AddVersionedApiExplorer();
```

Not surprisingly, swagger isn't showing any of the OData API definitions.  I cloned your samples directory and found that swagger doesn't seem to be working there, either.

![image](https://user-images.githubusercontent.com/8038952/123859803-f4b5f380-d8d9-11eb-8e58-f3757918b87a.png)

What is the recommended way to get OData 8 API definitions hooked up to swagger?

**Comment by xuzhg** [comment]
@twmillett You cloned "ODataRoutingSample" and run this sample, It can't work for the Swagger? 

It seems not true. Because, I just run it and send "http://localhost:5000/swagger". I got the following page.

![image](https://user-images.githubusercontent.com/9426627/124063899-ae02ef00-d9e8-11eb-9f20-a4e5e343d991.png)

**Comment by twmillett** [comment]
Ah, OK.  When I run ODataRoutingSample, it works as you describe.   Good to know it's supported.

I was running the ODataCustomizedSample, which fails with this exception.

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.NotSupportedException: Ambiguous HTTP method for action - ODataCustomizedSample.Controller.EmployeesController.Get (ODataCustomizedSample). Actions require an explicit HttpMethod binding for Swagger/OpenAPI 3.0
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by twmillett** [comment]
@xuzhg, is there a supported way to run OData v8.0 with api versioning?  I was wrong, above, about swagger not working in general (it was just the customized sample that was failing).  But, I still can't figure out how to get OData 8 wired up with aspnet-api-versioning.

The Odata controllers don't seem to be discovered unless I mark them with [ApiController], but that causes other problems and is recommended against in one of your readme's.

What I really need is a .net core 5 compatible version of OData that supports aspnet-api-versioning.  Does such a thing exist?

**Comment by commonsensesoftware** [comment]
sorry for the cross-post. @twmillett , @vishmittal just announced in dotnet/aspnet-api-versioning#677, official support is coming and is also here. pop on over for more details
