### ISSUE TITLE
Method 'Visit' in type 'QueryTokenVisitor' from assembly 'Microsoft.Azure.Cosmos.Table' does not have an implementation.

### ISSUE THREAD

**Issue by stevendarby** [OData/AspNetCoreOData#263]
Upgrading from 7.5.8 to 8.0.1, I get this exception at startup:
```
System.Reflection.ReflectionTypeLoadException
  HResult=0x80131602
  Message=Unable to load one or more of the requested types.
Method 'Visit' in type 'QueryTokenVisitor' from assembly 'Microsoft.Azure.Cosmos.Table, Version=1.0.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at AutoMapper.ServiceCollectionExtensions.<>c.<AddAutoMapperClasses>b__12_5(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapperClasses(IServiceCollection services, Action`2 configAction, IEnumerable`1 assembliesToScan, ServiceLifetime serviceLifetime)
   at AutoMapper.ServiceCollectionExtensions.AddAutoMapper(IServiceCollection services, Assembly[] assemblies)
   at [redacted].AddCore(IServiceCollection services) in [redacted]\Extensions\ServiceCollectionExtensions.cs:line 206
   at [redacted].Startup.ConfigureServices(IServiceCollection services) in [redacted]\Startup.cs:line 58
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at [redacted].<Main>d__0.MoveNext() in [redacted]\Program.cs:line 26
```

**Comment by Sreejithpin** [comment]
Can you please share a repro and the details
Also did you update EF

**Comment by pw-nable** [comment]
Hi, I have the same issue.
using Microsoft.AspNetCore.OData 8.0.1
and Microsoft.Azure.Cosmos.Table 1.0.8

when calling: **ExecuteQuerySegmentedAsync**

var query = new TableQuery<CosmosTable>().Where(TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, key));

var rows = await table.ExecuteQuerySegmentedAsync(query, null);

I get the same error as @stevendarby

**Comment by pw-nable** [comment]
Looks like I have found a workaround:
instead of 
var query = new TableQuery().Where(TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, key));

I used this query:

 var query = table.CreateQuery<CosmosTable>().Where(x => x.PartitionKey == key).AsTableQuery();
var rows = await table.ExecuteQuerySegmentedAsync(query, null);

Hope this helps!

**Comment by stevendarby** [comment]
> Can you please share a repro and the details
> Also did you update EF

I’ll try to put together a repro soon

**Comment by ChunliangGu** [comment]
@Sreejithpin got the same error as @pw-nable and @stevendarby . 
Packages: 
Microsoft.Azure.Cosmos.Table, v1.0.8
Microsoft.OData.Core v7.9.4

Target Framework:
.Net Framework 4.7.2

when calling: ExecuteQuerySegmentedAsync

```
var query = new TableQuery().Where(TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, key));

var rows = await table.ExecuteQuerySegmentedAsync(query, null);
```

And this error can be reproduced with Microsoft.OData.Core v7.9.0, v7.9.1, v7.9.2 and v7.9.3.
It's running well with Microsoft.OData.Core v7.8.3 and below

**Comment by ChunliangGu** [comment]
> Looks like I have found a workaround (at least in my case): instead of var query = new TableQuery().Where(TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, key));
> 
> I used this query:
> 
> var query = table.CreateQuery().Where(x => x.PartitionKey == key).AsTableQuery(); var rows = await table.ExecuteQuerySegmentedAsync(query, null);
> 
> Hope this helps!

**Comment by ChunliangGu** [comment]
> Looks like I have found a workaround (at least in my case): instead of var query = new TableQuery().Where(TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, key));
> 
> I used this query:
> 
> var query = table.CreateQuery().Where(x => x.PartitionKey == key).AsTableQuery(); var rows = await table.ExecuteQuerySegmentedAsync(query, null);
> 
> Hope this helps!

@pw-nable it doesn't work for me. and got another error
`{"Fluent methods may not be invoked on a Query created via CloudTable.CreateQuery<T>()"}`

and i also tried ".AsQueryable()", it doesnt work either.

**Comment by stevendarby** [comment]
Ok, some findings to share.

Firstly, the package Microsoft.Azure.Cosmos.Table is deprecated and people should migrate to its replacement if possible. It uses and old version of OData which is incompatible with OData ASP.NET Core 8.x and recent versions of 7.x too.

However, if you don't use the OData features of that package you may be ok. In my case, the startup error was due to configuring AutoMapper to scan every assembly in the current domain for mapping profiles; as a result it eagerly finds the incompatibility and throws. The solution for me was to narrow down the assemblies AutoMapper scans. No issues at runtime now.
