### ISSUE TITLE
DateTimeOffset deserialization doesn't seem to be supported.

### ISSUE THREAD

**Issue by ayo10** [OData/AspNetCoreOData#345]
If you try and create an entity that has a DateTimeOffset property, it causes a bad request to occur. The entity is null, and the model state will have an error in it with that property as the offender.

Specifically, the call from ODataResourceDeserializer.ApplyStructuralProperty makes it all the way to EdmPrimitiveHelper.ConvertPrimitiveValue, which doesn't handle DateTimeOffset types, which in turn causes it to call Convert.ChangeType which itself doesn't natively support converting strings to DateTimeOffset. Breakage ensues and a ValidationException is thrown.

The callstack:
>  at Microsoft.AspNetCore.OData.Edm.EdmPrimitiveHelper.ConvertPrimitiveValue(Object value, Type type, TimeZoneInfo timeZoneInfo) in D:\a\1\s\src\Microsoft.AspNetCore.OData\Edm\EdmPrimitiveHelper.cs:line 150
   at Microsoft.AspNetCore.OData.Formatter.Deserialization.DeserializationHelpers.SetDeclaredProperty(Object resource, EdmTypeKind propertyKind, String propertyName, Object propertyValue, IEdmProperty edmProperty, ODataDeserializerContext readContext) in D:\a\1\s\src\Microsoft.AspNetCore.OData\Formatter\Deserialization\DeserializationHelper.cs:line 97
   at Microsoft.AspNetCore.OData.Formatter.Deserialization.DeserializationHelpers.ApplyProperty(ODataProperty property, IEdmStructuredTypeReference resourceType, Object resource, IODataDeserializerProvider deserializerProvider, ODataDeserializerContext readContext) in D:\a\1\s\src\Microsoft.AspNetCore.OData\Formatter\Deserialization\DeserializationHelper.cs:line 65
   at Microsoft.AspNetCore.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyStructuralProperty(Object resource, ODataProperty structuralProperty, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext) in D:\a\1\s\src\Microsoft.AspNetCore.OData\Formatter\Deserialization\ODataResourceDeserializer.cs:line 519
   at Microsoft.AspNetCore.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyStructuralProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext) in D:\a\1\s\src\Microsoft.AspNetCore.OData\Formatter\Deserialization\ODataResourceDeserializer.cs:line 482
   at Microsoft.AspNetCore.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyResourceProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext) in D:\a\1\s\src\Microsoft.AspNetCore.OData\Formatter\Deserialization\ODataResourceDeserializer.cs:line 525
   at Microsoft.AspNetCore.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadResource(ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext) in D:\a\1\s\src\Microsoft.AspNetCore.OData\Formatter\Deserialization\ODataResourceDeserializer.cs:line 205
   at Microsoft.AspNetCore.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadInline(Object item, IEdmTypeReference edmType, ODataDeserializerContext readContext) in D:\a\1\s\src\Microsoft.AspNetCore.OData\Formatter\Deserialization\ODataResourceDeserializer.cs:line 126
   at Microsoft.AspNetCore.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadResource(ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext) in D:\a\1\s\src\Microsoft.AspNetCore.OData\Formatter\Deserialization\ODataResourceDeserializer.cs:line 191
   at Microsoft.AspNetCore.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadInline(Object item, IEdmTypeReference edmType, ODataDeserializerContext readContext) in D:\a\1\s\src\Microsoft.AspNetCore.OData\Formatter\Deserialization\ODataResourceDeserializer.cs:line 126
   at Microsoft.AspNetCore.OData.Formatter.Deserialization.ODataResourceDeserializer.<ReadAsync>d__1.MoveNext() in D:\a\1\s\src\Microsoft.AspNetCore.OData\Formatter\Deserialization\ODataResourceDeserializer.cs:line 89
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/libraries/System.Private.CoreLib/src/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 56

**Comment by xuzhg** [comment]
It is fixed in https://www.nuget.org/packages/Microsoft.AspNetCore.OData/8.0.4. 
Please file a new issue if you meet other questions. Thanks.
