### ISSUE TITLE
.NET 6 WebAPI + OData 8.0.4 - $top limit exceeded error

### ISSUE THREAD

**Issue by troncomputers** [OData/AspNetCoreOData#372]
Hi!
I did, probably, every possible setup for `MaxTop`.

**No. 1**
```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers().AddOData(options => EnableQueryFeatures(maxTopValue: 50));
var app = builder.Build();
```
**No. 2**
```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers().AddOData(options => options.Select().OrderBy().Filter().SetMaxTop(50));
var app = builder.Build();
```
**No. 3**
```csharp
    [Page(MaxTop = 50)]
    public class Document
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string SourceNumber { get; set; }
        public string CustomerName { get; set; }
        public DateTime Date { get; set; }
        public int Bufor { get; set; }
        public int Correction { get; set; }
        public int Type { get; set; }
        public string Net { get; set; }
        public string Gross { get; set; }
    }
```
**DocumentsController**
```csharp
        [HttpGet]
        [EnableQuery]
        public async Task<IActionResult> Get()
        {
            using (IDbConnection db = new SqlConnection(_configuration.GetConnectionString("SystemDatabase")))
            {
                return Ok(await db.QueryAsync<Document>("secret_query_string"));
            }
        }
```

Non of those works.

**Exception**
```
ExceptionMessage: "The limit of '0' for Top query has been exceeded. The value from the incoming request is '25'."
ExceptionType: "Microsoft.OData.ODataException"
Message: "The query specified in the URI is not valid. The limit of '0' for Top query has been exceeded. The value from the incoming request is '25'."
StackTrace: "   at Microsoft.AspNetCore.OData.Query.Validator.TopQueryValidator.Validate(TopQueryOption topQueryOption, ODataValidationSettings validationSettings)
   at Microsoft.AspNetCore.OData.Query.TopQueryOption.Validate(ODataValidationSettings validationSettings)
   at Microsoft.AspNetCore.OData.Query.Validator.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)
   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ValidateQuery(HttpRequest request, ODataQueryOptions queryOptions)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.CreateAndValidateQueryOptions(HttpRequest request, ODataQueryContext queryContext)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)"
```
**URL**
```
https://mysecreturl.com/api/documents?$filter=Type eq 302&$top=25
```

**Comment by karayanni** [comment]
@troncomputers what was the issue?
I'm facing the same problem

**Comment by troncomputers** [comment]
Yes, the error message is from frontend console. Public API did not have the `maxTop` defined.

**Comment by georgechond94** [comment]
Hey, @karayanni I am facing the exact same issue. Did you have any luck solving it? Thanks!

**Comment by karayanni** [comment]
@georgechond94 
not sure what the issue was, but currently the service is running smoothly with the max top defined by the action.Page(maxTopValue: 1000, pageSizeValue: 1000)
somethings to try out:

1. make sure you're calling the endpoint with the odata prefix not directly
2. make sure you're edm is well defined
3. try other filters, like select check if they work or only the top - if all don't then there is a wider issue
