### ISSUE TITLE
I'm getting an error, trying to get an array using the $select keyword in Odata

### ISSUE THREAD

**Issue by seregakup** [OData/AspNetCoreOData#535]
$select keyword doesn't work with collections

The Get method is:

```
            [EnableQuery]
            public async Task<IActionResult> Get()
            {
               var queryable = Task.FromResult(GetBaseQuery()
                        .ProjectTo<TR>(_mapperConfigProvider)
                        .AsNoTracking());
                return Ok(await queryable);
            } 

TR is MyEntityInfo
```

    I have installed the next packages:
    Microsoft.AspNetCore.OData 7.5.12
    Microsoft.OData.Client 7.9.4
    Microsoft.OData.Core 7.9.4
    Microsoft.OData.Edm 7.9.4
    OData V4
    .Net 5

I have a Db model

 ```
        public class MyEntityDb
           {       
             ...          
             public Guid[]? Ids { get; set; }          
             public Guid? Id{ get; set; }        
            ...             
           }    
```

and I have a Dto

```
    public class MyEntityInfo     
              {          
                ...         
                public Guid[]? Ids { get; set; }         
                public Guid? Id{ get; set; }        
                ...            
              }

```
When I'm sending request: `.../odata/MyEntity?$select=Id`
it works great I get:

 ```
"@odata.context": "https://localhost:88888/odata/$metadata#MyEntity(Id)",
        "value": [
            {
                "Id": "07ec6bce-a99b-4fd8-a6e2-1e634cb49352"
            },
            {
                "Id": "a23bdaf1-1e04-43d5-a14f-18ffd51d8eb2"
            } 
```

And request `.../odata/MyEntity` works great and return "the problem" array 

```
  "@odata.context": "https://localhost:88888/odata/$metadata#MyEntity",
        "value": [
                {
                   ...
                    "Id": "07ec6bce-a99b-4fd8-a6e2-1e634cb49352",
                    "Ids": [
                "07ec6bce-a99b-4fd8-a6e2-1e634cb49352"
                ],
                   ...
                }
```

But when I'm sending request: `.../odata/MyEntity?$select=Ids`

I get an error:
```
System.InvalidOperationException: The LINQ expression '$it' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluati
on explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
at System.Linq.Expressions.ExpressionVisitor.VisitLambda\[T\](Expression`1 node)    at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor\[TResult\](Expression query)
at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery\[TResult\](Expression query, Boolean async)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore\[TResult\](IDatabase database, Expression query, IModel model, Boolean async)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.\<\>c__DisplayClass12_0`1.<ExecuteAsync>b__0()    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync\[TResult\](Expression query, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync\[TResult\](Expression expression, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)    at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](Object value)    at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncEnumerable(ActionContext context, ObjectResult result, Object asyncEnumerable, Func`2 reader)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\<InvokeNextResultFilterAsync\>g__Awaited|29_0\[TFilter,TFilterAsync\](ResourceInvoker invoker, Task lastTask, Sta
te next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext\[TFilter,TFilterAsync\](State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
\--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\<InvokeFilterPipelineAsync\>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Ob
ject state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\<InvokeAsync\>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
at Microsoft.AspNetCore.Routing.EndpointMiddleware.\<Invoke\>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Shared.BaseStartup.\<\>c.\<\<Configure\>b__22_0\>d.MoveNext() 
\--- End of stack trace from previous location ---
at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests\[TContext\](IHttpApplication\`1 application)
```

**Comment by julealgon** [comment]
Have you tried simplifying your sample and stop using AutoMapper projections to see if that's related to the problem?

**Comment by xuzhg** [comment]
https://www.conradakunga.com/blog/saving-collections-of-primitives-in-entity-framework-core/

**Comment by seregakup** [comment]
Thank you guys for your responses, I'll  try your ideas. I gotta find some free time :)

**Comment by habbes** [comment]
Thanks @seregakup let us know how it goes.

**Comment by seregakup** [comment]
Hi guys, @julealgon 's idea about refusing using Automapper's ProjectTo method was right. The problem's root was  that ProjectTo creates its own expression tree and Odata creates its own expression tree and we get the conflict. Thanks to my collegue, he helped me with the problem :)
