### ISSUE TITLE
Error when function/action name contains keyword "On"

### ISSUE THREAD

**Issue by appvity-danhpham** [OData/AspNetCoreOData#568]
**Assemblies affected**
.NET 6.0
Microsoft.AspNetCore.OData 8.0.*

**Describe the bug**
Error when function/action name contains keyword "On"
Ex: 
/odata/SEChat/SE.GetStatusOnLineOfflineUser => error
/odata/SEChat/SE.StatusLineOfflineUserOn => error
/odata/SEChat/SE.OnGetStatusLineOfflineUser => success
/odata/SEChat/SE.GetStatusLineOfflineUser => success
/odata/SEChat/SE.GetStatusonLineOfflineUser => success

**EDM (CSDL) Model**
```C#
var builder = new ODataConventionModelBuilder();
            builder.Namespace = "SE";
            builder.ContainerName = "SE";
            builder.EnableLowerCamelCase();
builder.EntitySet<ChatInfo>("SEChat");
builder.EntityType<ChatInfo>().Collection.Function("GetStatusOnLineOfflineUser").ReturnsCollection<spv2_Org_GetOnlineOfflineUser_Result>().Parameter<int>("userId");
return builder.GetEdmModel();
```
**Program.cs**
```C#
builder.Services.AddControllers().AddOData(opt => {
    opt.Conventions.Remove(opt.Conventions.OfType<MetadataRoutingConvention>().First());
    opt.AddRouteComponents("odata", EdmModel.GetEdmModel())
        .Count()
        .OrderBy()
        .Filter()
        .Select()
        .Expand()
        .SkipToken()
        .SetMaxTop(300);
    opt.RouteOptions.EnableNonParenthesisForEmptyParameterFunction = true;
});
```
**Controller**
```C#
        [HttpGet]
        [EnableQuery]
        public IActionResult GetStatusOnLineOfflineUser(int userId)
        {
            //Code
            return Ok();
        }
```
**Request/Response**
```C#
Request: http://localhost:3481/odata/SEChat/SE.GetStatusOnLineOfflineUser(userId=1)
Response: 
Microsoft.OData.ODataException: The key value (SE.GetStatusOnLineOfflineUser(userId=1)) from request is not valid. The key value should be format of type 'Edm.Int32'.
 ---> Microsoft.OData.ODataException: Expected literal type token but found token 'SE'.
   at Microsoft.OData.UriParser.ExpressionLexerLiteralExtensions.ReadLiteralToken(ExpressionLexer expressionLexer)
   at Microsoft.OData.ODataUriUtils.ConvertFromUriLiteral(String value, ODataVersion version, IEdmModel model, IEdmTypeReference typeReference)
   at Microsoft.AspNetCore.OData.Routing.Template.KeySegmentTemplate.TryTranslate(ODataTemplateTranslateContext context)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.OData.Routing.Template.KeySegmentTemplate.TryTranslate(ODataTemplateTranslateContext context)
   at Microsoft.AspNetCore.OData.Routing.Template.DefaultODataTemplateTranslator.Translate(ODataPathTemplate path, ODataTemplateTranslateContext context)
   at Microsoft.AspNetCore.OData.Routing.ODataRoutingMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
**Expected behavior**
The function/action name should allow contains "On" keyword

**Screenshots**

**Additional context**
Please share your call stack or any error message

**Comment by julealgon** [comment]
Why do you believe this is at all related to the "On" string? That seems incredibly inlikely.

The error message suggests it is trying to pass `SE.GetStatusOnLineOfflineUser(userId=1)` as the ID for the `http://localhost:3481/odata/SEChatExx/{id}` route and failing since the string is not an int.

Please enable the OData route debugger and check if your route is detected as you expect before testing further.

**Comment by xuzhg** [comment]
@julealgon @appvity-danhpham It could be related to these codes at https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Routing/Conventions/OperationRoutingConvention.cs#L193-L202

**Comment by appvity-danhpham** [comment]
Thanks @julealgon, @xuzhg

**Comment by xuzhg** [comment]
Merged. Please file new issue if you have further questions.
