### ISSUE TITLE
[EnableQuery] attribute fails when null value is processed

### ISSUE THREAD

**Issue by drozee** [OData/AspNetCoreOData#609]
When the OData attribute is enabled and a null value is return before the query is applied (query might be a select, expand , 

System.ArgumentException
  HResult=0x80070057
  Message=Object of type 'Microsoft.OData.ODataError' cannot be converted to type 'Microsoft.Wufb.Deployments.DeploymentPolicy'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.Bind(Object source, SelectExpandBinderContext context)
   at Microsoft.AspNetCore.OData.Query.SelectExpandQueryOption.ApplyTo(Object entity, ODataQuerySettings settings)
   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplySelectExpand[T](T entity, ODataQuerySettings querySettings)
   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplyTo(Object entity, ODataQuerySettings querySettings)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ApplyQuery(Object entity, ODataQueryOptions queryOptions)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext)
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeNextActionFilterAsync>g__Awaited|10_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<<InvokeInnerFilterAsync>g__Awaited|13_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeFilterPipelineAsync>g__Awaited|19_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<<InvokeAsync>g__Awaited|17_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<<Invoke>g__AwaitRequestTask|6_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Online.IntelligentUpdate.Service.Middleware.RequestValidationMiddleware.<Invoke>d__4.MoveNext() in C:\git\repos\iu\src\services\WebApps\UpdateAPI\Middleware\RequestValidationMiddleware.cs:line 94

  This exception was originally thrown at this call stack:
    [External Code]
    Microsoft.Online.IntelligentUpdate.Service.Middleware.RequestValidationMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext, Microsoft.Online.IntelligentUpdate.Core.Telemetry.Interfaces.ILogger) in RequestValidationMiddleware.cs

My expectation is to be able to route the null case differently to avoid this problem.

**Comment by drozee** [comment]
Here is the helper class that will fix this issue.  Once you have the class as part of your code on the method that already 
has the attribute [EnableQuery] change it to [CustomEnableQuery].

```
    using Microsoft.AspNetCore.Mvc.Filters;
    using Microsoft.AspNetCore.OData.Query;

    /// <summary>
    /// Class for enabling a custom query attribute
    /// </summary>
    public class CustomEnableQueryAttribute : EnableQueryAttribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomEnableQueryAttribute"/> class.
        /// </summary>
        public CustomEnableQueryAttribute()
        {
        }

        /// <summary>
        /// If not found we will stop the call stack here
        /// </summary>
        /// <param name="actionExecutedContext">actionExecutedContext</param>
        public override void OnActionExecuted(ActionExecutedContext actionExecutedContext)
        {
            if (actionExecutedContext.Result.GetType() != typeof(Microsoft.AspNetCore.Mvc.NotFoundObjectResult))
            {
                base.OnActionExecuted(actionExecutedContext);
            }
        }
    }
```

**Comment by julealgon** [comment]
@drozee  why would you return `null` in the first place? If you want to model an endpoint that may or may not return an entity and still allow queries on that, you should be using OData's `SingleResult` type with a backing single-value queryable. OData will then handle this for you and return 404 if the query doesn't return anything.

Please clarify if this is your scenario. If so, I would consider your approach with the custom attribute here undesirable and would not recommend anyone else from copying it.
