### ISSUE TITLE
Intermittent error on serialization in aspnetcore odata 7.5.4 

### ISSUE THREAD

**Issue by houbi56** [OData/AspNetCoreOData#61]
Getting intermittent serialization errors in 7.5.4 under load, worked without issues in 7.5.2

We use a class IgnoreDefaultEntityPropertiesSerializer : ODataResourceSerializer that on CreateStructuralProperty returns null if
the value of the created ODataproperty is of primitive type and has a default value.
Prop is created by calling base.CreateStructuralProperty(structuralProperty, resourceContext);

The error happens when multiple (16) concurrent calls are made from a webpage, typically 10-20% of the time one of the calls will fail with the error:
System.InvalidOperationException: The EDM instance of type '[xxx Nullable=True]' is missing the property 'yyy'..

--
System.InvalidOperationException: The EDM instance of type '[xxx Nullable=True]' is missing the property 'yyy'.
at Microsoft.AspNet.OData.ResourceContext.GetPropertyValue(String propertyName)
at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateStructuralProperty(IEdmStructuralProperty structuralProperty, ResourceContext resourceContext)
at [ournamespace].Server.Configuration.Serialization.IgnoreDefaultEntityPropertiesSerializer.CreateStructuralProperty(IEdmStructuralProperty structuralProperty, ResourceContext resourceContext)
at Microsoft.AspNet.OData.Formatter.Serialization.ODataResourceSerializer.CreateStructuralPropertyBag(SelectExpandNode selectExpandNode, ResourceContext resourceContext)

**Comment by xuzhg** [comment]
@houbi56 Do you mind share me a repo (maybe a github repro) to dig more?

**Comment by houbi56** [comment]
https://github.com/houbi56/OData754ConcurrencyError

**Comment by houbi56** [comment]
@xuzhg Have you had the time to look at it?

**Comment by houbi56** [comment]
See [https://github.com/OData/WebApi/issues/2390](https://github.com/OData/WebApi/issues/2390)

**Comment by houbi56** [comment]
Confirm fixed in #2397
