### ISSUE TITLE
Overloaded properties cannot be expanded

### ISSUE THREAD

**Issue by Dean-ZhenYao-Wang** [OData/AspNetCoreOData#644]
**Assemblies affected**
Microsoft.AspNetCore.OData 8.0.10

**Describe the bug**
When my model is non-inherited and the attributes are not overloaded, I can get the expanded data normally.
However, when my model changes to inherit from the parent model and overloads an attribute in the parent model, the overloaded attribute of the current model can no longer be expanded.

**Reproduce steps**
The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.

**Data Model**
Please share your Data model, for example, your C# class.

**EDM (CSDL) Model**
`<?xml version="1.0" encoding="utf-8"?>
  <edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
      <Schema Namespace="BaseDB" xmlns="http://docs.oasis-open.org/odata/ns/edm">
        <EntityType Name="人员">
          <Key>
            <PropertyRef Name="Key" />
          </Key>
          <Property Name="ID" Type="Edm.String" />
          <Property Name="密码" Type="Edm.String" />
          <Property Name="姓名" Type="Edm.String" />
          <Property Name="性别" Type="BaseDB.Enum.性别Enum" Nullable="false" />
          <Property Name="邮件" Type="Edm.String" />
          <Property Name="手机" Type="Edm.String" />
          <Property Name="Code" Type="Edm.String" />
          <Property Name="头像" Type="Edm.String" />
          <Property Name="年龄" Type="Edm.Int32" />
          <Property Name="生日" Type="Edm.DateTimeOffset" />
          <Property Name="所属的组织列表" Type="Collection(BaseDB.人员_组织)" />
          <Property Name="Key" Type="Edm.Guid" Nullable="false" />
          <Property Name="说明" Type="Edm.String" />
          <Property Name="CreateUser" Type="Edm.Guid" Nullable="false" />
          <Property Name="CreateDate" Type="Edm.DateTimeOffset" Nullable="false" />
          <Property Name="UpdateUser" Type="Edm.Guid" />
          <Property Name="UpdateDate" Type="Edm.DateTimeOffset" />
          <Property Name="Remark" Type="Edm.String" />
          <NavigationProperty Name="所属人员类列表" Type="Collection(BaseDB.人员_人员类)" />
          <NavigationProperty Name="特性列表" Type="Collection(BaseDB.人员特性)" />
        </EntityType>
        <EntityType Name="人员类">
          <Key>
            <PropertyRef Name="Key" />
          </Key>
          <Property Name="Key" Type="Edm.Guid" Nullable="false" />
          <Property Name="ID" Type="Edm.String" />
          <Property Name="说明" Type="Edm.String" />
          <Property Name="CreateUser" Type="Edm.Guid" Nullable="false" />
          <Property Name="CreateDate" Type="Edm.DateTimeOffset" Nullable="false" />
          <Property Name="UpdateUser" Type="Edm.Guid" />
          <Property Name="UpdateDate" Type="Edm.DateTimeOffset" />
          <Property Name="Remark" Type="Edm.String" />
          <NavigationProperty Name="父类列表" Type="Collection(BaseDB.人员类)" />
          <NavigationProperty Name="子类列表" Type="Collection(BaseDB.人员类)" />
          <NavigationProperty Name="特性列表" Type="Collection(BaseDB.人员类特性)" ContainsTarget="true" />
          <NavigationProperty Name="可访问的菜单列表" Type="Collection(BaseDB.人员类_菜单)" />
        </EntityType>
        <EntityType Name="人员_人员类">
          <Key>
            <PropertyRef Name="Key" />
          </Key>
          <Property Name="Key" Type="Edm.Guid" Nullable="false" />
          <Property Name="人员Key" Type="Edm.Guid" />
          <Property Name="人员类Key" Type="Edm.Guid" />
          <Property Name="CreateUser" Type="Edm.Guid" Nullable="false" />
          <Property Name="CreateDate" Type="Edm.DateTimeOffset" Nullable="false" />
          <Property Name="UpdateUser" Type="Edm.Guid" />
          <Property Name="UpdateDate" Type="Edm.DateTimeOffset" />
          <Property Name="Remark" Type="Edm.String" />
          <NavigationProperty Name="人员" Type="BaseDB.人员">
            <ReferentialConstraint Property="人员Key" ReferencedProperty="Key" />
          </NavigationProperty>
          <NavigationProperty Name="人员类" Type="BaseDB.人员类">
            <ReferentialConstraint Property="人员类Key" ReferencedProperty="Key" />
          </NavigationProperty>
        </EntityType>
        <EntityType Name="人员类特性">
          <Key>
            <PropertyRef Name="Key" />
          </Key>
          <Property Name="Key" Type="Edm.Guid" Nullable="false" />
          <Property Name="ID" Type="Edm.String" />
          <Property Name="说明" Type="Edm.String" />
          <Property Name="特性类型" Type="BaseDB.Enum.类特性类型Enum" Nullable="false" />
          <Property Name="值" Type="Edm.String" />
          <Property Name="值的度量单位" Type="Edm.String" />
          <Property Name="父特性Key" Type="Edm.Guid" />
          <Property Name="所属类Key" Type="Edm.Guid" />
          <Property Name="CreateUser" Type="Edm.Guid" Nullable="false" />
          <Property Name="CreateDate" Type="Edm.DateTimeOffset" Nullable="false" />
          <Property Name="UpdateUser" Type="Edm.Guid" />
          <Property Name="UpdateDate" Type="Edm.DateTimeOffset" />
          <Property Name="Remark" Type="Edm.String" />
          <NavigationProperty Name="所属类" Type="BaseDB.人员类">
            <ReferentialConstraint Property="所属类Key" ReferencedProperty="Key" />
          </NavigationProperty>
          <NavigationProperty Name="子项列表" Type="Collection(BaseDB.人员类特性)" />
          <NavigationProperty Name="父特性" Type="BaseDB.人员类特性">
            <ReferentialConstraint Property="父特性Key" ReferencedProperty="Key" />
          </NavigationProperty>
        </EntityType>
        <EntityType Name="人员类_菜单">
          <Key>
            <PropertyRef Name="Key" />
          </Key>
          <Property Name="Key" Type="Edm.Guid" Nullable="false" />
          <Property Name="人员类Key" Type="Edm.Guid" />
          <Property Name="菜单Key" Type="Edm.Guid" Nullable="false" />
          <Property Name="菜单" Type="BaseDB.菜单" />
          <Property Name="CreateUser" Type="Edm.Guid" Nullable="false" />
          <Property Name="CreateDate" Type="Edm.DateTimeOffset" Nullable="false" />
          <Property Name="UpdateUser" Type="Edm.Guid" />
          <Property Name="UpdateDate" Type="Edm.DateTimeOffset" />
          <Property Name="Remark" Type="Edm.String" />
          <NavigationProperty Name="人员类" Type="BaseDB.人员类">
            <ReferentialConstraint Property="人员类Key" ReferencedProperty="Key" />
          </NavigationProperty>
        </EntityType>
        <ComplexType Name="菜单">
          <Property Name="MicroAppKey" Type="Edm.Guid" />
          <Property Name="Key" Type="Edm.Guid" Nullable="false" />
          <Property Name="名称" Type="Edm.String" />
          <Property Name="编号" Type="Edm.String" />
          <Property Name="序号" Type="Edm.Int32" Nullable="false" />
          <Property Name="Url" Type="Edm.String" />
          <Property Name="ICON" Type="Edm.String" />
          <Property Name="上级菜单Key" Type="Edm.Guid" />
          <Property Name="下级菜单列表" Type="Collection(BaseDB.菜单)" />
          <Property Name="上级菜单" Type="BaseDB.菜单" />
          <Property Name="CreateUser" Type="Edm.Guid" Nullable="false" />
          <Property Name="CreateDate" Type="Edm.DateTimeOffset" Nullable="false" />
          <Property Name="UpdateUser" Type="Edm.Guid" />
          <Property Name="UpdateDate" Type="Edm.DateTimeOffset" />
          <Property Name="Remark" Type="Edm.String" />
          <NavigationProperty Name="MicroApp" Type="BaseDB.MicroApps" />
          <NavigationProperty Name="可访问的人员类列表" Type="Collection(BaseDB.人员类_菜单)" />
        </ComplexType>
        <EntityType Name="MicroApps">
          <Key>
            <PropertyRef Name="Key" />
          </Key>
          <Property Name="Key" Type="Edm.Guid" Nullable="false" />
          <Property Name="Name" Type="Edm.String" Nullable="false" />
          <Property Name="ActivePath" Type="Edm.String" Nullable="false" />
          <Property Name="LoadScriptMode" Type="Edm.String" />
          <Property Name="Title" Type="Edm.String" />
          <Property Name="Entry" Type="Edm.String" />
          <Property Name="EntryContent" Type="Edm.String" />
          <Property Name="菜单列表" Type="Collection(BaseDB.菜单)" />
          <Property Name="CreateUser" Type="Edm.Guid" Nullable="false" />
          <Property Name="CreateDate" Type="Edm.DateTimeOffset" Nullable="false" />
          <Property Name="UpdateUser" Type="Edm.Guid" />
          <Property Name="UpdateDate" Type="Edm.DateTimeOffset" />
          <Property Name="Remark" Type="Edm.String" />
        </EntityType>
        <EntityType Name="人员特性">
          <Key>
            <PropertyRef Name="Key" />
          </Key>
          <Property Name="Key" Type="Edm.Guid" Nullable="false" />
          <Property Name="ID" Type="Edm.String" />
          <Property Name="说明" Type="Edm.String" />
          <Property Name="值" Type="Edm.String" />
          <Property Name="值的度量单位" Type="Edm.String" />
          <Property Name="父特性Key" Type="Edm.Guid" />
          <Property Name="MapsToKey" Type="Edm.Guid" />
          <Property Name="所属对象Key" Type="Edm.Guid" />
          <Property Name="CreateUser" Type="Edm.Guid" Nullable="false" />
          <Property Name="CreateDate" Type="Edm.DateTimeOffset" Nullable="false" />
          <Property Name="UpdateUser" Type="Edm.Guid" />
          <Property Name="UpdateDate" Type="Edm.DateTimeOffset" />
          <Property Name="Remark" Type="Edm.String" />
          <NavigationProperty Name="父特性" Type="BaseDB.人员特性">
            <ReferentialConstraint Property="父特性Key" ReferencedProperty="Key" />
          </NavigationProperty>
          <NavigationProperty Name="MapsTo" Type="BaseDB.人员类特性">
            <ReferentialConstraint Property="MapsToKey" ReferencedProperty="Key" />
          </NavigationProperty>
          <NavigationProperty Name="所属对象" Type="BaseDB.人员">
            <ReferentialConstraint Property="所属对象Key" ReferencedProperty="Key" />
          </NavigationProperty>
          <NavigationProperty Name="子项列表" Type="Collection(BaseDB.人员特性)" />
        </EntityType>
        <ComplexType Name="人员_组织">
          <Property Name="Key" Type="Edm.Guid" Nullable="false" />
          <Property Name="人员Key" Type="Edm.Guid" Nullable="false" />
          <Property Name="组织Key" Type="Edm.Guid" Nullable="false" />
          <Property Name="组织" Type="BaseDB.组织" />
          <Property Name="CreateUser" Type="Edm.Guid" Nullable="false" />
          <Property Name="CreateDate" Type="Edm.DateTimeOffset" Nullable="false" />
          <Property Name="UpdateUser" Type="Edm.Guid" />
          <Property Name="UpdateDate" Type="Edm.DateTimeOffset" />
          <Property Name="Remark" Type="Edm.String" />
          <NavigationProperty Name="人员" Type="BaseDB.人员" />
        </ComplexType>
        <ComplexType Name="组织">
          <Property Name="Key" Type="Edm.Guid" Nullable="false" />
          <Property Name="编号" Type="Edm.String" />
          <Property Name="序号" Type="Edm.Int32" Nullable="false" />
          <Property Name="名称" Type="Edm.String" />
          <Property Name="全名" Type="Edm.String" />
          <Property Name="上级组织Key" Type="Edm.Guid" />
          <Property Name="下辖的人员列表" Type="Collection(BaseDB.人员_组织)" />
          <Property Name="CreateUser" Type="Edm.Guid" Nullable="false" />
          <Property Name="CreateDate" Type="Edm.DateTimeOffset" Nullable="false" />
          <Property Name="UpdateUser" Type="Edm.Guid" />
          <Property Name="UpdateDate" Type="Edm.DateTimeOffset" />
          <Property Name="Remark" Type="Edm.String" />
        </ComplexType>
      </Schema>
      <Schema Namespace="BaseDB.Enum" xmlns="http://docs.oasis-open.org/odata/ns/edm">
        <EnumType Name="类特性类型Enum">
          <Member Name="类类型" Value="0" />
          <Member Name="实例类型" Value="1" />
          <Member Name="缺省类型" Value="2" />
        </EnumType>
        <EnumType Name="性别Enum">
          <Member Name="男" Value="0" />
          <Member Name="女" Value="1" />
          <Member Name="未知" Value="2" />
        </EnumType>
      </Schema>
      <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
        <EntityContainer Name="Container">
          <EntitySet Name="Person" EntityType="BaseDB.人员">
            <NavigationPropertyBinding Path="所属的组织列表/人员" Target="Person" />
          </EntitySet>
          <EntitySet Name="PersonnelClass" EntityType="BaseDB.人员类">
            <NavigationPropertyBinding Path="父类列表" Target="PersonnelClass" />
            <NavigationPropertyBinding Path="子类列表" Target="PersonnelClass" />
          </EntitySet>
        </EntityContainer>
      </Schema>
    </edmx:DataServices>
  </edmx:Edmx>`

**Request/Response**
request
curl -X 'GET' \
  'https://localhost:5001/api/PersonnelClass?%24expand=%E7%89%B9%E6%80%A7%E5%88%97%E8%A1%A8' \
  -H 'accept: */*'
  
response body.
{
  "$id": "1",
  "ClassName": "System.Reflection.AmbiguousMatchException",
  "Message": "Ambiguous match found.",
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": "   at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
  at System.Type.GetProperty(String name, BindingFlags bindingAttr)
  at System.Type.GetProperty(String name)
  at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.CreatePropertyValueExpression(QueryBinderContext context, IEdmStructuredType elementType, IEdmProperty edmProperty, Expression source, FilterClause filterClause, ComputeClause computeClause)
  at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.BuildExpandedProperty(QueryBinderContext context, Expression source, IEdmStructuredType structuredType, IEdmNavigationProperty navigationProperty, ExpandedReferenceSelectItem expandedItem, IList`1 includedProperties)
  at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.BuildPropertyContainer(QueryBinderContext context, Expression source, IEdmStructuredType structuredType, IDictionary`2 propertiesToExpand, IDictionary`2 propertiesToInclude, IList`1 computedProperties, ISet`1 autoSelectedProperties, Boolean isSelectingOpenTypeSegments)
  at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.ProjectElement(QueryBinderContext context, Expression source, SelectExpandClause selectExpandClause, IEdmStructuredType structuredType, IEdmNavigationSource navigationSource)
  at Microsoft.AspNetCore.OData.Query.Expressions.SelectExpandBinder.BindSelectExpand(SelectExpandClause selectExpandClause, QueryBinderContext context)
  at Microsoft.AspNetCore.OData.Query.Expressions.BinderExtensions.ApplyBind(ISelectExpandBinder binder, IQueryable source, SelectExpandClause selectExpandClause, QueryBinderContext context)
  at Microsoft.AspNetCore.OData.Query.SelectExpandQueryOption.ApplyTo(IQueryable queryable, ODataQuerySettings settings)
  at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplySelectExpand[T](T entity, ODataQuerySettings querySettings)
  at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ApplyTo(IQueryable query, ODataQuerySettings querySettings)
  at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ApplyQuery(IQueryable queryable, ODataQueryOptions queryOptions)
  at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
  at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext, Object responseValue, IQueryable singleResultCollection, ControllerActionDescriptor actionDescriptor, HttpRequest request)
  at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuted(ActionExecutedContext actionExecutedContext)
  at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
  at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location where exception was thrown ---
  at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)",
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": null,
  "HResult": -2147475171,
  "Source": "System.Private.CoreLib",
  "WatsonBuckets": null
}
**Expected behavior**
I expect the generator to get the data normally and contain the expanded properties

**Screenshots**
![image](https://user-images.githubusercontent.com/26154837/180605836-9c3f72c0-c542-4af9-b66b-efa5c770e8b1.png)

**Additional context**
N.A

**Comment by Dean-ZhenYao-Wang** [comment]
Problem solved
This is the model I'm having trouble with：
` public abstract class 类Entity : Base_Entity
    {
        [Key]
        public virtual Guid Key { get; set; }
        public virtual string ID { get; set; }
        public virtual string 说明 { get; set; }
        public virtual IList<类特性Entity> 特性列表 { get; set; } = new List<类特性Entity>();
    }`
`public partial class 人员类 : 类Entity
    {
        [Contained]
        public new virtual IList<人员类特性> 特性列表 { get; set; } = new List<人员类特性>();
    }`
When I put the `Microsoft.AspNetCore.OData.Query.Expressions. SelectExpandBinder.cs` code files  Line 235 by `propertyInfo = source.Type.GetProperty(propertyName);` Change to `propertyInfo = source.Type.GetProperties().Where(m => m.Name.Equals(propertyName)).FirstOrDefault();` Then the problem was solved.
