### ISSUE TITLE
Non-EDM approach not working.

### ISSUE THREAD

**Issue by RobTF** [OData/AspNetCoreOData#71]
Hi,

I have a repo on Github which shows an example API using OData. The example works well using the 7.5.2 library on .NET Core 3.1, but not the 8.0.0 preview 3 version on .NET 5.0. Would it be possible to understand why the latter fails?

[https://github.com/RobTF/AspNetCoreODataExamples/tree/master/NonEdmApproach](https://github.com/RobTF/AspNetCoreODataExamples/tree/master/NonEdmApproach)

For example, if I call `http://localhost:5000/api/accounts` (OData 7.5.2) I get the following response;
```
{
    "items": [
        {
            "id": "1c82f39e-462e-4e76-ac84-7fb9ca4827b9",
            "name": "Customer 1"
        },
        {
            "id": "cd755916-4834-42c4-93f2-8933bb57f62d",
            "name": "Customer 2"
        },
        {
            "id": "826d5e58-85d2-4ae5-932f-a491f8cbc979",
            "name": "Customer 3"
        }
    ],
    "nextPageLink": null,
    "count": null
}
```

Calling the same endpoint using OData 8.0.0-preview3 I get the following;
```
System.ArgumentNullException: Value cannot be null. (Parameter 'model')
   at Microsoft.AspNetCore.OData.Query.ODataQueryContext..ctor(IEdmModel model, Type elementClrType, ODataPath path)
   at Microsoft.AspNetCore.OData.Query.ODataQueryParameterBindingAttribute.ODataQueryParameterBinding.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

The code is as close to equivalent as possible. I'm hoping I've just missed something.

**Comment by xuzhg** [comment]
@RobTF 8.x is originally designed around with a given Edm model so far.

**Comment by xuzhg** [comment]
@RobTF I just finished some codes to enable non-model scenario at https://github.com/OData/AspNetCoreOData/commit/e5774486bb72cb4caf6cbb0d3b5810e1c0db293e

The nightly build is running for this commit.  Once the build is green, would you please try the latest nightly?

![image](https://user-images.githubusercontent.com/9426627/107007929-07bc0180-6748-11eb-9564-e1d1c9b5e651.png)

**Comment by RobTF** [comment]
Nice, thanks! I'll try updating my play projects and post my findings.

**Comment by xuzhg** [comment]
The nightly build is ok. If you are interested in, you can try: Microsoft.AspNetCore.OData.8.0.0-Nightly202102051314.nupkg

the nightly feed is : https://www.myget.org/F/webapinetcore

Below is my test based on your repro:

![image](https://user-images.githubusercontent.com/9426627/107068184-25fc1e80-6795-11eb-9712-995dd6bb6add.png)

**Comment by RobTF** [comment]
Yep, looks like it's working. Is it possible to override the keys to make everything camel case? With no EDM model I guess it will need to be attribute driven?

**Comment by jakakonda** [comment]
Hi,

I am also interested in Non-EDM approach with lower camel case. Is there any built in method? Alternatively, `ODataQueryOptions` could be preprocessed, but the solution is far from ideal.

Second, might need to open a separate issues. how is it with server side paging?
There an example in the old documentation (the second one), but it does not work any more. Cast to `IEnumerable` fails (returns null) and paginated result does not have `count` property (if result is hard-coded for example), but a normal enumerable is returned without the pagination wrapper.
https://docs.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/supporting-odata-query-options#server-driven-paging

**Comment by xuzhg** [comment]
For the case sensitive, see docs at: https://github.com/OData/AspNetCoreOData/blob/main/docs/camel_case_scenarios.md

If you have other questions, or concerns, please file a new issue for us. Thanks.
