### ISSUE TITLE
Empty $filter in request causes service to return 500 due to ODataException

### ISSUE THREAD

**Issue by devlie** [OData/AspNetCoreOData#725]
**Assemblies affected**
ASP.NET Core OData 7.x and 8.x

**Describe the bug**
When user calls service with empty $filter, for e.g. `https://localhost/foo?$filter=` 

**Reproduce steps**
1. Create ASP.NET Core 3.1 REST API project.
2. Enable OData.
3. Call the service with empty $filter.

**Request/Response**
Request: `https://localhost/foo?$filter=` 
Response: service returns 500, with the model binding code throwing exception.

**Expected behavior**
Service returns 400. While I can handle the particular exception in my handler, it seems weird that I have to do that for simple user error like this.

**Additional context**

```csharp
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
Microsoft.OData.ODataException: The value for OData query '$filter' cannot be empty.
   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.ThrowIfEmpty(String queryValue, String queryName)
   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.BuildQueryOptions(IDictionary`2 queryParameters)
   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.Initialize(ODataQueryContext context)
   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions..ctor(ODataQueryContext context, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions`1..ctor(ODataQueryContext context, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.ODataQueryParameterBindingAttribute.ODataQueryParameterBinding.CreateODataQueryOptions[T](ODataQueryContext context, HttpRequest request)
   at Microsoft.AspNetCore.OData.Query.ODataQueryParameterBindingAttribute.ODataQueryParameterBinding.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Eds.Cdp.ManagedContentService.TestHookMiddleware.InvokeAsync(HttpContext httpContext) in D:\ADU\MCS\src\ManagedContentService\TestHookMiddleware.cs:line 103
   at Microsoft.Identity.ServiceEssentials.Extensions.AspNetCoreMiddleware.MiseMiddleware.InvokeInternal(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Eds.Platform.Identity.ServiceToServiceAuthMiddleware.InvokeAsync(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by devlie** [comment]
@xuzhg, any update on this? Thanks.

**Comment by mikepizzo** [comment]
@xuzhg -- we should return the 400 in these types of cases, right? Is the issue due to interaction between our exception handling and the AspNetCore exception handler middleware?

**Comment by gathogojr** [comment]
Fixed by https://github.com/OData/AspNetCoreOData/issues/725
