### ISSUE TITLE
Using Newtonsoftjson with oData 8.x.x return "Self referencing loop Issue"

### ISSUE THREAD

**Issue by mtehseennawaz** [OData/AspNetCoreOData#749]
**Versions:**
    net core 6.0
    oData 8.0.11

**Issue started** when I have upgraded my application from dotnet core 3.1 to net 6.0 and oData 7.5.0 to 8.0.11 .

**Issue Description:**
I have two controllers in my dotnet application. In first controller I am using Microsoft.AspNetCore.JsonPatch which require NewtonsoftJson, so I had registered Newtonsoftjson in my startup.cs:
           services.AddControllers().AddNewtonsoftJson();

In second controller I am using oData, So when I apply select query it return Status Code 500 with message (*"Newtonsoft Self referencing loop detected"* ). If I remove Newtonsoftjson from startup it start working, but I need Newtonsoftjson for my other controller where I am using JsonPatch. So, I can't remove it. Dotnet core 3.1 and oData 7.5.0 work fine with Newtonsoftjson. 

**Query:**
  select query that i am using :
  https://localhost:44398/v1.0/Applications?$filter Model eq 2571ab2-e5cc-4d84-a94f-45881cfdd401 & $select=ApplicationID

 **Response Message**

![image](https://user-images.githubusercontent.com/54778153/203263396-2f7d2839-9c25-499e-b0a4-f0a9d66ff46a.png)

**Comment by julealgon** [comment]
The fact that you are getting a Newtonsoft exception in your OData GET endpoint means the endpoint is not being treated as an OData endpoint, but as an MVC endpoint instead.

I assume you were using an OData endpoint before otherwise you'd be seeing this error earlier.

Please provide the following:
- output of the `$odata` debug endpoint (check readme for instructions on how to enable it)
- your controller code and affected action 
- edm setup code
- startup section with OData setup

**Comment by xuzhg** [comment]
@mtehseennawaz You need to install 'https://www.nuget.org/packages/Microsoft.AspNetCore.OData.NewtonsoftJson'

Here's the source codes:
'https://github.com/OData/AspNetCoreOData/tree/main/src/Microsoft.AspNetCore.OData.NewtonsoftJson' 

Here's the sample: https://github.com/OData/AspNetCoreOData/tree/main/sample/ODataNewtonsoftJsonSample

**Comment by mtehseennawaz** [comment]
**Query:**
https://localhost:44398/v1.0/ApplicationMetadata?$filter=Model eq 941f0ab2-e5cc-4d84-a94f-45881cfdd4b1&$select=ApplicationID

**Logs:**

Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'declaringType' with type 'Microsoft.OData.Edm.EdmEntityType'. Path '[0].model.schemaElements[0].declaredKey[0]'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Formatters.NewtonsoftJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultAsync>g__Logged|22_0(ResourceInvoker invoker, IActionResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at iModelJsAnalysisService.Startup.<>c.<<Configure>b__8_0>d.MoveNext() in D:\iModelJSAnalysisService\Src\iModelJsAnalysisService\Startup.cs:line 216
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   


**Controller code and affected action:**

![image](https://user-images.githubusercontent.com/54778153/203493308-dddff3db-eab9-4e8c-89a0-1210b8357ea5.png)

**EDM setup:**
![image](https://user-images.githubusercontent.com/54778153/203493452-3d353330-8129-4bf1-ab2a-cff75a78c562.png)


**Startup section with OData setup:**

![image](https://user-images.githubusercontent.com/54778153/203493678-44468cf6-f606-4d9f-b211-16179d615c90.png)

![image](https://user-images.githubusercontent.com/54778153/203493788-da065a3a-5f33-4bb6-b2f4-1e95a9014bbc.png)

**Comment by gathogojr** [comment]
@mtehseennawaz
Like @julealgon observed, you shared this request Uri https://localhost:44398/v1.0/ApplicationMetadata?$filter=Model eq 941f0ab2-e5cc-4d84-a94f-45881cfdd4b1&$select=ApplicationID
Looking at your OData service configuration code, you defined a route prefix - `odata` - which you don't have on the request Uri.
Your stack traces also don't have any references to OData library classes.

Can you try the suggestion that @xuzhg suggested...

**Comment by mtehseennawaz** [comment]
Thanks all for quick help. Installing (https://www.nuget.org/packages/Microsoft.AspNetCore.OData.NewtonsoftJson) and changing route prefix from odata to v1.0 fix the issue.

**Comment by xuzhg** [comment]
Thanks. Close it. Please file new issue if you have further questions or concerns.
