### ISSUE TITLE
Incomplete JSON output is returned when querying navigation property that has at least one complex property.

### ISSUE THREAD

**Issue by danleydmello** [OData/AspNetCoreOData#760]
Incomplete JSON output is returned when querying navigation property that has at least one complex property.

To reproduce the problem use [ODataDynamicModel ](https://github.com/OData/AspNetCoreOData/tree/main/sample/ODataDynamicModel)sample.
1. In MyDataSource.cs, add EdmComplexType property to DetailInfo entity.
2. Add some value to this complex property in CreateDetailInfo()

Now run this query :
`http://localhost:4527/odata/mydatasource/Products(1)/DetailInfo`

Note that output is truncated and does not include complex property of DetailInfo :

`{"@odata.context":"http://localhost:4527/odata/mydatasource/$metadata#Products/ns.DetailInfo/$entity","ID":88,"Title":"abc_detailinfo"   <no results after this>`

I see this exception in debug:

_Microsoft.OData.ODataException
  HResult=0x80131509
  Message=The type 'ns.DetailInfo' does not inherit from and is not a base type of 'ns.Product'. The type of 'KeySegments' must be related to the Type of the EntitySet.
  Source=Microsoft.OData.Core
  StackTrace:
   at Microsoft.OData.UriParser.ExceptionUtil.ThrowIfTypesUnrelated(IEdmType type, IEdmType secondType, String segmentName)
   at Microsoft.OData.UriParser.KeySegment..ctor(IEnumerable`1 keys, IEdmEntityType edmType, IEdmNavigationSource navigationSource)
   at Microsoft.OData.UriParser.ODataPathExtensions.AddKeySegment(ODataPath path, IEnumerable`1 keys, IEdmEntityType edmType, IEdmNavigationSource navigationSource)
   at Microsoft.OData.ODataWriterCore.AppendEntitySetKeySegment(ODataPath odataPath, Boolean throwIfFail)
   at Microsoft.OData.ODataWriterCore.EnterScope(WriterState newState, ODataItem item)
   at Microsoft.OData.ODataWriterCore.WriteStartNestedResourceInfoImplementation(ODataNestedResourceInfo nestedResourceInfo)
   at Microsoft.OData.ODataWriterCore.<>c__DisplayClass65_0.<WriteStartAsync>b__0()
   at Microsoft.OData.TaskUtils.GetTaskForSynchronousOperation(Action synchronousOperation)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.<WriteComplexPropertiesAsync>d__19.MoveNext() in D:\githubrepos\AspNetCoreOData\src\Microsoft.AspNetCore.OData\Formatter\Serialization\ODataResourceSerializer.cs:line 839

  This exception was originally thrown at this call stack:
    [External Code]
    Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteComplexPropertiesAsync(Microsoft.AspNetCore.OData.Formatter.Serialization.SelectExpandNode, Microsoft.AspNetCore.OData.Formatter.ResourceContext, Microsoft.OData.ODataWriter) in ODataResourceSerializer.cs_
		
	
Note: Complex type works when expanding the navigation property.

**Comment by xuzhg** [comment]
It is related to this PR: https://github.com/OData/odata.net/pull/2552

**Comment by danleydmello** [comment]
@xuzhg , thanks for the reference,.
Will it fix my issue once the odata.net PR gets merged? What timeline we are looking at for odata.net and Microsoft.AspNetCore.OData patch release with this fix?

**Comment by xuzhg** [comment]
We just released 7.13.0 ODL. But, it seems this version doesn't fix this issue. 
We'd find resource to find the root cause and fix this issue.

**Comment by danleydmello** [comment]
@xuzhg , Thanks for the update. Do you know if the problem is in odata.net library or its in AspNetOData core ? 
Any idea what time frame we are looking at ?

**Comment by xuzhg** [comment]
> 

So far, I think it's from odata.net lib. The problem is that we want to 'calculate' a path for each sub-complex property.

Because complex property could contain navigation property, we should need that path to 'calculate' the context path for navigation property again, even though we don't know whether the complex does have navigation property or not.

https://github.com/OData/odata.net/pull/2552 fixes the problem for the containment navigation property. I'd like to spend time understanding the complex property.

**Comment by premiaware** [comment]
Hi, I have same issue in .net 6 and odata 8.0.12 

I have this object


  public class TelefonoDescrittivo 
    {
        public string? Etichetta { get; set; }
    }

 public class Uffici2
{
}

    public partial class UfficiExt : Uffici2
    {
         public List<TelefonoDescrittivo>? Telefoni { get; set; }
    }

in my Model declare:
            builderWeb.EntitySet<Uffici2>("Uffici2");
            builderWeb.EntitySet<UfficiExt>("UfficiExt");
            builderWeb.EntityType<UfficiExt>().DerivesFrom<Uffici2>();

when in call my bonded function in the controller

https://localhost:7146/odata/landingpageimmobili/Ufficio

and ufficio return type "UfficiExt" with complex data i receive this exception.

Microsoft.OData.ODataException: The type 'FastHomeDB.Models.UfficiExt' does not inherit from and is not a base type of 'FastHomeDB.Models.LandingPageImmobili'. The type of 'KeySegments' must be related to the Type of the EntitySet.
   at Microsoft.OData.UriParser.ExceptionUtil.ThrowIfTypesUnrelated(IEdmType type, IEdmType secondType, String segmentName)
   at Microsoft.OData.UriParser.ODataPathExtensions.AddKeySegment(ODataPath path, IEnumerable`1 keys, IEdmEntityType edmType, IEdmNavigationSource navigationSource)
   at Microsoft.OData.ODataWriterCore.AppendEntitySetKeySegment(ODataPath odataPath, Boolean throwIfFail)
   at Microsoft.OData.ODataWriterCore.EnterScope(WriterState newState, ODataItem item)
   at Microsoft.OData.ODataWriterCore.WriteStartNestedResourceInfoImplementation(ODataNestedResourceInfo nestedResourceInfo)
   at Microsoft.OData.TaskUtils.GetTaskForSynchronousOperation[TArg1,TArg2](Action`2 synchronousOperation, TArg1 arg1, TArg2 arg2)
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteComplexPropertiesAsync(SelectExpandNode selectExpandNode, ResourceContext resourceContext, ODataWriter writer)
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteResourceAsync(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInlineAsync(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectAsync(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)
   at Microsoft.AspNetCore.OData.Formatter.ODataOutputFormatterHelper.WriteToStreamAsync(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, HttpRequest request, IHeaderDictionary requestHeaders, IODataSerializerProvider serializerProvider)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
