### ISSUE TITLE
Problem using $select & $top together in EntityFramework Core Oracle

### ISSUE THREAD

**Issue by chajere** [OData/AspNetCoreOData#8]
When I want to retrive specific columns (column1, column2) the generated query is like:

```
 SELECT :TypedProperty_1 "ModelID", N'NAME' "Name", "t"."Column1" "Value", N'NUMBER0' "Name", "t"."Column2" "Value"
FROM "SomeTable" "t"
FETCH FIRST :TypedProperty_2 ROWS ONLY
```

This is not allowed by Oracle
![image](https://user-images.githubusercontent.com/13526144/94974401-b7980e80-04cb-11eb-8f41-89f0745baedf.png)

Once I removed the $top it works correctly
![image](https://user-images.githubusercontent.com/13526144/94974498-fded6d80-04cb-11eb-8acb-4068fdbd68cf.png)

**This is the error detail**
Microsoft.EntityFrameworkCore.Database.Command: Error: 2020-10-02 16:08:22.856434 ThreadID:28  (ERROR)   OracleRelationalCommand.ExecuteReaderAsync() :  Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00918: column ambiguously defined
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Oracle.EntityFrameworkCore.Storage.Internal.OracleRelationalCommandBuilderFactory.OracleRelationalCommandBuilder.OracleRelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Database.Command: Error: Failed executing DbCommand (245ms) [Parameters=[:TypedProperty_1='?' (Size = 2000), :TypedProperty_0='?' (Size = 12), :TypedProperty_2='?' (DbType = Int32)], CommandType='Text', CommandTimeout='0']
SELECT :TypedProperty_1 "ModelID", N'NAME' "Name", "t"."NAME" "Value", N'NUMBER0' "Name", "t"."NUMBER0" "Value"
FROM "TINWSYS" "t"
WHERE "t"."NUMBER0" = :TypedProperty_0
ORDER BY "t"."NUMBER0"
FETCH FIRST :TypedProperty_2 ROWS ONLY

**Comment by GowrishKumar** [comment]
I also have a similar issue when using oracle, i'm using the latest Oracle.EntityFrameworkCore 5.21.1 and latest Microsoft.AspNetCore.OData 7.5.7

**Comment by kvansaders** [comment]
This happened to me - the issue is with the Oracle EF Core provider - this happens in versions earlier than 18c.  My workaround was to purchase the DevArt Oracle EF Core provider, and the library worked fine after that.
