### ISSUE TITLE
SelectExpandQueryValidator throws when $selecting complex property (EDM loaded from CSDL)

### ISSUE THREAD

**Issue by mjameson-se** [OData/AspNetCoreOData#829]
Using the latest on main (trying to debug the other issues I've run into in released versions)
> Unable to cast object of type 'Microsoft.OData.Edm.Csdl.CsdlSemantics.CsdlSemanticsNamedTypeReference' to type 'Microsoft.OData.Edm.IEdmComplexTypeReference'."
at Microsoft.AspNetCore.OData.Query.Validator.SelectExpandQueryValidator.GetStructuredType(IEdmTypeReference typeRef)
   at Microsoft.AspNetCore.OData.Query.Validator.SelectExpandQueryValidator.ValidatePathSelectItem(PathSelectItem pathSelectItem, SelectExpandValidatorContext validatorContext)
   at Microsoft.AspNetCore.OData.Query.Validator.SelectExpandQueryValidator.ValidateSelectExpand(SelectExpandClause selectExpandClause, SelectExpandValidatorContext validatorContext)
   at Microsoft.AspNetCore.OData.Query.Validator.SelectExpandQueryValidator.Validate(SelectExpandQueryOption selectExpandQueryOption, ODataValidationSettings validationSettings)
   at Microsoft.AspNetCore.OData.Query.SelectExpandQueryOption.Validate(ODataValidationSettings validationSettings)
   at Microsoft.AspNetCore.OData.Query.Validator.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)
   at Microsoft.AspNetCore.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.ValidateQuery(HttpRequest request, ODataQueryOptions queryOptions)
   at Microsoft.AspNetCore.OData.Query.EnableQueryAttribute.OnActionExecuting(ActionExecutingContext actionExecutingContext)

This error does not occur in the released 8.0.12 version. Note that `GetStructuredType` seems to be superfluous as odata.net has an extension method `.ToStructuredType()` which works correctly in this case.

**Comment by xuzhg** [comment]
@mjameson-se would you please try the latest main code bases?
