### ISSUE TITLE
Cannot use single endpoint using Route attribute and with AddRouteComponents

### ISSUE THREAD

**Issue by komdil** [OData/AspNetCoreOData#851]
**Assemblies affected**
Microsoft.AspNetCore.OData 8.0.12

**Describe the bug**
I have a controller that has 4 actions: CRUD. I want to use OData only on Read. My controller should fit api/[controller] template. 
I was not able to do that with OData. It is opening two endpoints or showing some errors

**Reproduce steps**
My controller: 

```
[Route("api/[controller]")]
    public class CustomersController : ControllerBase
    {
        private static Random random = new Random();
        private static List<Customer> customers = new List<Customer>(
            Enumerable.Range(1, 3).Select(idx => new Customer
            {
                Id = idx,
                Name = $"Customer {idx}",
                Orders = new List<Order>(
                    Enumerable.Range(1, 2).Select(dx => new Order
                    {
                        Id = (idx - 1) * 2 + dx,
                        Amount = random.Next(1, 9) * 10
                    }))
            }));

        [HttpGet()]
        [EnableQuery]
        public ActionResult Get()
        {
            return Ok(customers);
        }

        [HttpPut()]
        public ActionResult Put()
        {
            return Ok();
        }

        [HttpPost()]
        public ActionResult Post()
        {
            return Ok();
        }

        [HttpDelete]
        public ActionResult Delete()
        {
            return Ok();
        }
    }
```

I am using `AddRouteComponents("api", modelBuilder.GetEdmModel()))`, because my controller has `api `prefix

It is throwing an error: 

```
Microsoft.AspNetCore.Routing.Matching.AmbiguousMatchException: The request matched multiple endpoints. Matches: 

WebApplication3.Controllers.CustomersController.Get (WebApplication3)
WebApplication3.Controllers.CustomersController.Get (WebApplication3)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ReportAmbiguity(CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.ProcessFinalCandidates(HttpContext httpContext, CandidateState[] candidateState)
   at Microsoft.AspNetCore.Routing.Matching.DefaultEndpointSelector.SelectAsync(HttpContext httpContext, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Expected behavior**
It should use endpoint without an error

**Comment by julealgon** [comment]
Duplicate of a combination of:
- https://github.com/OData/AspNetCoreOData/issues/430
- https://github.com/OData/AspNetCoreOData/issues/431

Please check those and see if they can help you out.

**Comment by xuzhg** [comment]
@komdil It seems there is one endpoint from 'conventional routing', and the other endpoint (the same route template) from attribute routing.  Either remove '[Route("api/[controller]")]' or change the prefix 'AddRouteComponents'. Thanks.

**Comment by xuzhg** [comment]
@julealgon I also want to make a decision for:

If there's an attribute routing defined, skip the convention routing. What do you think?

**Comment by julealgon** [comment]
> @julealgon I also want to make a decision for:
> 
> If there's an attribute routing defined, skip the convention routing. What do you think?

I think that would be a good idea overall, yes. Would eliminate these weird clashes that are really hard to understand if you are not deeply familiar with the conventions.

It is also a common pattern in other scenarios so there is precedent for it, like serialization (take `DataContract`): if the user doesn't specify anything, a "convention" is used. If the user provides any manual `[DataMember]` attributes, then the serializer only honors those.

**Comment by komdil** [comment]
> @komdil It seems there is one endpoint from 'conventional routing', and the other endpoint (the same route template) from attribute routing. Either remove '[Route("api/[controller]")]' or change the prefix 'AddRouteComponents'. Thanks.

When I remove Route attribute it and put api/odata in AddRouteComponents, I will be available to use Get action only in /api/odata/customers route which is good. However, My other actions Put, Post, Delete will not be in /api/customers. It will be in /customers, so I will need to define api prefix in every action which doesn't seems good

**Comment by julealgon** [comment]
@komdil please double check the conventions here if you want to go the conventional route:
- https://learn.microsoft.com/en-us/odata/webapi/built-in-routing-conventions

Remove the `HttpPut/Get/Post/etc` attributes and just rename the methods accordingly and add the required parameters.
