### ISSUE TITLE
Enum values case sensitivity

### ISSUE THREAD

**Issue by marcopelegrini** [OData/AspNetCoreOData#853]
Is there a way to allow case insensitivity for enum values?

For instance: `/odata/v1/apps?$expand=scores($filter=type in ('overall','Basic'))`

When ScoreType is defined as:

```
public enum ScoreType
{
    Overall = 0,
    Basic = 1,
}
```

I get an error here, but from what I could see, I'd have to override the FilterBinder which is not a very friendly task.
Any suggestions?

```
      System.ArgumentException: Requested value 'overall' was not found.
         at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
         at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
         at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
         at System.Enum.Parse(Type enumType, String value)
         at Microsoft.AspNetCore.OData.Query.Expressions.QueryBinder.RetrieveClrTypeForConstant(IEdmTypeReference edmTypeReference, QueryBinderContext context, Object& value)
```

**Comment by xuzhg** [comment]
@marcopelegrini 
1) If you only want to support lowercase, you can put [EnumMember] on the Overall to change it as lowercase
2) if you want to support any case, overriding FilterBinder could be an option.
