### ISSUE TITLE
custom serializer converts long to string, but throw an exception

### ISSUE THREAD

**Issue by gaozejie** [OData/AspNetCoreOData#895]
**Assemblies affected**
.net6、ASP.NET Core OData 8.1.1

**Describe the bug**
I created a serializer that converts long type to string type, but threw an Microsoft.OData.ODataException: An incompatible primitive type 'Edm.String[Nullable=True]' was found for an item that was expected to be of type 'Edm.Int64[Nullable=False]'

**Reproduce steps**

```
public class ODataSerializerProviderNew : ODataSerializerProvider // IODataSerializerProvider
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ODataSerializerProvider"/> class.
    /// </summary>
    /// <param name="serviceProvider">The root container.</param>
    public ODataSerializerProviderNew(IServiceProvider serviceProvider) : base(serviceProvider)
    {
    }

    /// <inheritdoc />
    public override IODataEdmTypeSerializer GetEdmTypeSerializer(IEdmTypeReference edmType)
    {
        //Console.WriteLine($"xxxxxxxx   {edmType}");

        if (edmType.IsPrimitive() && edmType.PrimitiveKind() == EdmPrimitiveTypeKind.Int64)
        {
            return new CustomLongStringSerializer();
        }

        return base.GetEdmTypeSerializer(edmType);
    }

    /// <inheritdoc />
    public override IODataSerializer GetODataPayloadSerializer(Type type, HttpRequest request)
    {
        //Console.WriteLine($"ssssssss   {type}");
        return base.GetODataPayloadSerializer(type, request);
    }
}

public class CustomLongStringSerializer : ODataPrimitiveSerializer
{
    public CustomLongStringSerializer()
    {
    }

    public override ODataPrimitiveValue CreateODataPrimitiveValue(object graph, IEdmPrimitiveTypeReference primitiveType, ODataSerializerContext writeContext)
    {
        if (graph is long longValue)
        {

            return new ODataPrimitiveValue(longValue.ToString());

        }

        return base.CreateODataPrimitiveValue(graph, primitiveType, writeContext);
    }
}

// Program.cs
                  opt.AddRouteComponents("oq", model, s =>
                  {
                      s.AddSingleton<ODataResourceSerializer>(x => new ODataResourceSerializerNew(x.GetRequiredService<IODataSerializerProvider>()));

                  s.AddSingleton<ODataPrimitiveSerializer>(x => new CustomLongStringSerializer());



```

**Data Model**

```
public class DemoDto
    {
        /// <summary>
        /// 
        /// </summary>
        [Key]
        public long RecordId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Region { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public long RegionId { get; set; }
        

}
```

**EDM (CSDL) Model**

```
<?xml version="1.0" encoding="utf-8"?>
  <edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
    <edmx:DataServices>
      <Schema Namespace="Nxin.Template.Application.Dtos" xmlns="http://docs.oasis-open.org/odata/ns/edm">
        <EntityType Name="DemoDto">
          <Key>
            <PropertyRef Name="RecordId" />
          </Key>
          <Property Name="RecordId" Type="Edm.Int64" Nullable="false" />
          <Property Name="Region" Type="Edm.String" Nullable="false" />
          <Property Name="RegionId" Type="Edm.Int64" Nullable="false" />
         

    </EntityType>
  </Schema>
  <Schema Namespace="Default" xmlns="http://docs.oasis-open.org/odata/ns/edm">
    <EntityContainer Name="Container">
      <EntitySet Name="DemoOData" EntityType="Nxin.Template.Application.Dtos.DemoDto" />
    </EntityContainer>
  </Schema>
</edmx:DataServices>

</edmx:Edmx>
```

**Request/Response**

```
curl -X 'GET' \
  'http://localhost:5276/oq/DemoOData' \
  -H 'accept: application/json;odata.metadata=minimal;odata.streaming=true'
```

**Expected behavior**
I want to convert long type to string type when returning to the front-end.  e.g. 11111111111111 -> "11111111111111"

**Screenshots**
![image](https://user-images.githubusercontent.com/16096320/233934458-24122c95-a73c-43e2-86c3-c883305e2b11.png)

**Additional context**

```
 An unhandled exception was thrown by the application. Microsoft.OData.ODataException: An incompatible primitive type 'Edm.String[Nullable=True]' was found for an item that was expected to be of type 'Edm.Int64[Nullable=False]'.
   at Microsoft.OData.ValidationUtils.ValidateMetadataPrimitiveType(IEdmTypeReference expectedTypeReference, IEdmTypeReference typeReferenceFromValue)
   at Microsoft.OData.JsonLight.ODataJsonLightValueSerializer.WritePrimitiveValueAsync(Object value, IEdmTypeReference actualTypeReference, IEdmTypeReference expectedTypeReference)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WritePrimitivePropertyAsync(ODataPrimitiveValue primitiveValue, Boolean isOpenPropertyType)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WritePropertyAsync(ODataProperty property, IEdmStructuredType owningType, Boolean isTopLevel, IDuplicatePropertyNameChecker duplicatePropertyNameChecker, ODataResourceMetadataBuilder metadataBuilder)
   at Microsoft.OData.JsonLight.ODataJsonLightPropertySerializer.WritePropertiesAsync(IEdmStructuredType owningType, IEnumerable`1 properties, Boolean isComplexValue, IDuplicatePropertyNameChecker duplicatePropertyNameChecker, ODataResourceMetadataBuilder metadataBuilder)
   at Microsoft.OData.JsonLight.ODataJsonLightWriter.StartResourceAsync(ODataResource resource)
   at Microsoft.OData.ODataWriterCore.<>c.<<WriteStartResourceImplementationAsync>b__196_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.OData.ODataWriterCore.InterceptExceptionAsync[TArg0](Func`3 action, TArg0 arg0)
   at Microsoft.OData.ODataWriterCore.WriteStartResourceImplementationAsync(ODataResource resource)
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteResourceAsync(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInlineAsync(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteResourceSetAsync(IEnumerable enumerable, IEdmTypeReference resourceSetType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectInlineAsync(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSetSerializer.WriteObjectAsync(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)
   at Microsoft.AspNetCore.OData.Formatter.ODataOutputFormatterHelper.WriteToStreamAsync(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, HttpRequest request, IHeaderDictionary requestHeaders, IODataSerializerProvider serializerProvider)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.OData.Routing.ODataRouteDebugMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by xuzhg** [comment]
@gaozejie Why don't use the 'IEEE754Compatible=true'.

The IEEE754Compatible=true format parameter indicates that the service MUST serialize Edm.Int64 and Edm.Decimal numbers  as strings. 

You can use it in $format query option for Accept request header with value as:
application/json;IEEE754Compatible=true

**Comment by gaozejie** [comment]
Yes, but I tried both methods before and they didn't work.
![image](https://user-images.githubusercontent.com/16096320/234450688-9d422786-0346-4ce6-a2fb-a48f3ed1e27d.png)

**Comment by gaozejie** [comment]
@xuzhg Do I need to add configuration in the program ?
