### ISSUE TITLE
Odata not working with Edm model loaded from file

### ISSUE THREAD

**Issue by ipr9n** [OData/AspNetCoreOData#896]
**Assemblies affected**
ASP.NET Core OData 8.x

**Describe the bug**
When trying to read a edm model from a file, Odata stops working.

**Reproduce steps**
Create two entity:
```
 public class User
    {
        public string Id { get; set; }
        public string Name { get; set; }
    }

    public class Book
    {
        public string Id { get; set; }
        public User Author { get; set; }
    }
```

Create two controllers:
 ```
public class BooksController : ODataController
    {
        [EnableQuery]
        public IActionResult Get()
        {
            
            return Ok(new[] { new Book { Id = "1" }, new Book { Id = "2" } });
        }

        [EnableQuery]
        public IActionResult Get(string key)
        {
            return Ok(new Book { Id = key });
        }
    }
```
and
 ```
 public class UsersController : ODataController
    {
        [EnableQuery]
        public IActionResult Get()
        {

            return Ok(new[] { new User { Id = "1" }, new User { Id = "2" } });
        }

        [EnableQuery]
        public IActionResult Get(string key)
        {
            return Ok(new User { Id = key });
        }
    }
```
Startup class:
 ```
public class Startup
    {
        public Startup(IConfiguration configuration, IWebHostEnvironment env)
        {
            Configuration = configuration;
            this.Env = env;
        }
      
        public IConfiguration Configuration { get; }
        public IWebHostEnvironment Env { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors();

            services
                .AddMvc(o =>
                {
                    o.EnableEndpointRouting = false;
                })
                .AddJsonOptions(options =>
                {
                    options.JsonSerializerOptions.AllowTrailingCommas = true;
                    options.JsonSerializerOptions.IgnoreNullValues = true;
                    options.JsonSerializerOptions.NumberHandling = JsonNumberHandling.AllowReadingFromString;
                });

            services.AddControllers()
                .AddApplicationPart(Assembly.GetExecutingAssembly())
                .AddOData((setupAction, serviceProvider) =>
                {
                    setupAction.EnableAttributeRouting = true;
                    setupAction.RouteOptions.EnableUnqualifiedOperationCall = true;
                    setupAction.RouteOptions.EnableQualifiedOperationCall = true;
                    setupAction.RouteOptions.EnableKeyAsSegment = true;
                    setupAction.RouteOptions.EnableKeyInParenthesis = true;
                    setupAction.QuerySettings.EnableCount = true;
                    setupAction.QuerySettings.EnableSelect = true;
                    setupAction.QuerySettings.EnableExpand = true;
                    setupAction.QuerySettings.EnableSkipToken = true;
                    setupAction.QuerySettings.EnableFilter = true;
                    setupAction.QuerySettings.EnableOrderBy = true;
                    setupAction.QuerySettings.MaxTop = null;
                    setupAction.AddRouteComponents("api", GetEdmModel(), serviceCollection =>
                    {
                    });
                });

            services.AddHealthChecks();

            services.AddRouting();
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env, ILogger<Startup> logger)
        {
            app.UseCors(x => x
                .AllowAnyOrigin()
                .AllowAnyMethod()
                .AllowAnyHeader());

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseRouting();
            app.UseMvc();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            app.UseHttpsRedirection();

            app.UseHealthChecks("/health");
        }

        private IEdmModel GetEdmModel()
        {
            ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
            builder.Namespace = "MyNamespace";
            builder.EntitySet<User>("Users");
            builder.EntitySet<Book>("Books");

            var edmModel = builder.GetEdmModel();
            SaveEdmModel(edmModel);

            return edmModel;
        }

        private void SaveEdmModel(IEdmModel model)
        {
            using (var writer = XmlWriter.Create("edmModel.xml"))
            {
                model.TryWriteSchema(writer, out var errors);
            }
        }
    }
```
After that, both entities must be registered and we can run the project and request books or a book by key.

![image](https://user-images.githubusercontent.com/57600027/234287511-cb0335f2-d3f7-4b2f-a89c-0c6cec198586.png)
![image](https://user-images.githubusercontent.com/57600027/234287331-484ec592-e6fd-4d64-a82e-25c3a65995ba.png)

Everything is working.
When we first started the project, we saved the schema to a file.
Let's change the GetEdmModel() method to read from a file

```
private IEdmModel GetEdmModel()
        {
            using (var reader = XmlReader.Create("edmModel.xml"))
            {
                var readers = new[] { reader };
                SchemaReader.TryParse(readers, out var edmModel, out var errors);

                return edmModel;
            }
        }
```

Let's restart the project and try to execute the same queries.

![image](https://user-images.githubusercontent.com/57600027/234288494-c43ded9f-0e07-4025-ab6b-a768f532151f.png)

We can see that **odata.context is missing.**

![image](https://user-images.githubusercontent.com/57600027/234288926-41c20a72-f319-4a71-bf8a-1139ee33ad73.png)
The same situation

And if we trying to expand author, then we will receive new error:
URI:  **https://localhost:44387/api/Books/2?$expand=Author**

```
Microsoft.OData.ODataException: A type named 'OdataEdmModelBug.Models.Book' could not be resolved by the model. When a model is available, each type name must resolve to a valid type.
   at Microsoft.OData.TypeNameOracle.ResolveAndValidateTypeName(IEdmModel model, String typeName, EdmTypeKind expectedTypeKind, Nullable`1 expectStructuredType, IWriterValidator writerValidator)
   at Microsoft.OData.TypeNameOracle.ResolveAndValidateTypeFromTypeName(IEdmModel model, IEdmStructuredType expectedType, String typeName, IWriterValidator writerValidator)
   at Microsoft.OData.ODataWriterCore.GetResourceType(ODataResourceBase resource)
   at Microsoft.OData.ODataWriterCore.ValidateResourceForResourceSet(ODataResourceBase resource, ResourceBaseScope resourceScope)
   at Microsoft.OData.ODataWriterCore.<>c.<<WriteStartResourceImplementationAsync>b__194_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.OData.ODataWriterCore.InterceptExceptionAsync[TArg0](Func`3 action, TArg0 arg0)
   at Microsoft.OData.ODataWriterCore.WriteStartResourceImplementationAsync(ODataResource resource)
   at Microsoft.OData.ODataWriterCore.WriteStartAsync(ODataResource resource)
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteResourceAsync(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInlineAsync(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectAsync(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)
   at Microsoft.AspNetCore.OData.Formatter.ODataOutputFormatterHelper.WriteToStreamAsync(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, HttpRequest request, IHeaderDictionary requestHeaders, IODataSerializerProvider serializerProvider)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Warning: The response has already started, the error page middleware will not be executed.
Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer: Error: Connection ID "18302628903618874841", Request ID "40000ddb-0004-fe00-b63f-84710c7967bb": An unhandled exception was thrown by the application.

Microsoft.OData.ODataException: A type named 'OdataEdmModelBug.Models.Book' could not be resolved by the model. When a model is available, each type name must resolve to a valid type.
   at Microsoft.OData.TypeNameOracle.ResolveAndValidateTypeName(IEdmModel model, String typeName, EdmTypeKind expectedTypeKind, Nullable`1 expectStructuredType, IWriterValidator writerValidator)
   at Microsoft.OData.TypeNameOracle.ResolveAndValidateTypeFromTypeName(IEdmModel model, IEdmStructuredType expectedType, String typeName, IWriterValidator writerValidator)
   at Microsoft.OData.ODataWriterCore.GetResourceType(ODataResourceBase resource)
   at Microsoft.OData.ODataWriterCore.ValidateResourceForResourceSet(ODataResourceBase resource, ResourceBaseScope resourceScope)
   at Microsoft.OData.ODataWriterCore.<>c.<<WriteStartResourceImplementationAsync>b__194_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.OData.ODataWriterCore.InterceptExceptionAsync[TArg0](Func`3 action, TArg0 arg0)
   at Microsoft.OData.ODataWriterCore.WriteStartResourceImplementationAsync(ODataResource resource)
   at Microsoft.OData.ODataWriterCore.WriteStartAsync(ODataResource resource)
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteResourceAsync(Object graph, ODataWriter writer, ODataSerializerContext writeContext, IEdmTypeReference expectedType)
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectInlineAsync(Object graph, IEdmTypeReference expectedType, ODataWriter writer, ODataSerializerContext writeContext)
   at Microsoft.AspNetCore.OData.Formatter.Serialization.ODataResourceSerializer.WriteObjectAsync(Object graph, Type type, ODataMessageWriter messageWriter, ODataSerializerContext writeContext)
   at Microsoft.AspNetCore.OData.Formatter.ODataOutputFormatterHelper.WriteToStreamAsync(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, HttpRequest request, IHeaderDictionary requestHeaders, IODataSerializerProvider serializerProvider)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
```

**EDM (CSDL) Model**
```
<?xml version="1.0" encoding="utf-8"?>
<Schema Namespace="MyNamespace" xmlns="http://docs.oasis-open.org/odata/ns/edm">
	<EntityType Name="User">
		<Key>
			<PropertyRef Name="Id" />
		</Key>
		<Property Name="Id" Type="Edm.String" Nullable="false" />
		<Property Name="Name" Type="Edm.String" />
	</EntityType>
	<EntityType Name="Book">
		<Key>
			<PropertyRef Name="Id" />
		</Key>
		<Property Name="Id" Type="Edm.String" Nullable="false" />
		<NavigationProperty Name="Author" Type="MyNamespace.User" />
	</EntityType>
	<EntityContainer Name="Container">
		<EntitySet Name="Users" EntityType="MyNamespace.User" />
		<EntitySet Name="Books" EntityType="MyNamespace.Book">
			<NavigationPropertyBinding Path="Author" Target="Users" />
		</EntitySet>
	</EntityContainer>
</Schema>
```

**Expected behavior**
The Edm model is loaded and all odata functions are working as expected.

**Notes**
The same behaviour using CsdlReader and CsdlWriter.
$metadata endpoint works after loading through file.

**Comment by xuzhg** [comment]
@pr9n Loading the model from 'CSDL string/file/or other streams'  doesn't work because there's no type mapping built between Edm type and C# type (CLR type). 

By default, if you build the model using ODataModelBuilder or ODataConventionModelBuilder, the builder builds a mapping between Edm Type and CLR type using this annotation 'https://github.com/OData/ModelBuilder/blob/main/src/Microsoft.OData.ModelBuilder/Annotations/ClrTypeAnnotation.cs'
However, there's no such annotation on the Edm model if you load the model from CSDL.

Couple of workarounds are to:
1) And the mapping manually when you load the model from CSDL. 
```C#
IEdmModel model = LoadModel();
IEdmType edmType = model.FindType(....);
Type clrType = typeof(your c# typename);
model.SetAnnotationValue<ClrTypeAnnotation>(edmType, new ClrTypeAnnotation(clrType));
```

2) Use the IODataTypeMapper. 
Implement this interface https://github.com/OData/AspNetCoreOData/blob/main/src/Microsoft.AspNetCore.OData/Edm/IODataTypeMapper.cs
 Then, call 
`model.SetTypeMapper(...);`
It could be easy if you can derive from 'DefaultODataTypeMapper' to override certain virtual methods.

Let us know if you still have the issues.

**Comment by xuzhg** [comment]
By the way, if the Edm full type name is same as the CRL type full name (Case Sensitive) and the CLR types are loaded in the assemblies, you don't need to do anything, it should work. 
I noticed You reset the namespace using these codes:
```C#
builder.Namespace = "MyNamespace";
```
So, that's the 'root cause'.

**Comment by ipr9n** [comment]
Thanks, everything seems to be working, but there is one additional question.

My method for getting and saving edmModel
```
 private IEdmModel GetEdmModel()
        {
            ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
            builder.Namespace = "MyNamespace";
            builder.EntitySet<User>("Users");

            var booksEntitySet = builder.EntitySet<Book>("Books");
            var booksAction = booksEntitySet.EntityType.Action("MyAction");
            booksAction.ReturnsFromEntitySet(typeof(Book), "Books");

            var booksCollectionAction = booksEntitySet.EntityType.Collection.Action("MyAction");
            booksCollectionAction.ReturnsCollectionFromEntitySet(typeof(Book), "Books");

            var edmModel = builder.GetEdmModel();
            SaveEdmModel(edmModel);

            return edmModel;
        }

        private void SaveEdmModel(IEdmModel model)
        {
            using (var writer = XmlWriter.Create("edmModel.xml"))
            {
                //   model.TryWriteSchema(writer, out var errors);
                CsdlWriter.TryWriteCsdl(model, writer, CsdlTarget.OData, out var errors);
            }
        }
```

Here we can see that I added two actions.
They are also added to the controller.

```
  [EnableQuery]
        [HttpPost]
        public IActionResult MyAction([FromBody] Book book)
        {
            return Ok(book);
        }

        [EnableQuery]
        [HttpPost]
        public IActionResult MyAction([FromODataUri] string key, [FromBody] Book book)
        {
            return Ok(book);
        }
```

We start the project, try to execute the action and see that the action works.
![image](https://github.com/OData/AspNetCoreOData/assets/57600027/7fdb080d-ae41-4e03-b362-6ce924616a28)
![image](https://github.com/OData/AspNetCoreOData/assets/57600027/4fa37017-8767-44f1-8e0d-a01782c28592)

Let's stop the project and change the method to get the edmModel.
Let's try to read from a file.

``` 
private IEdmModel GetEdmModel()
        {
            using (var reader = XmlReader.Create("edmModel.xml"))
            {
                var readers = new[] { reader };
                CsdlReader.TryParse(reader, out var edmModel, out var errors);

                edmModel.SchemaElements.ToList().ForEach(x =>
                {
                    Type clrTypeBook = typeof(Book);
                    Type clrTypeUser = typeof(User);

                    if (x.Name.Contains("Book"))
                        edmModel.SetAnnotationValue<ClrTypeAnnotation>(x, new ClrTypeAnnotation(clrTypeBook));
                    else if (x.Name.Contains("User"))
                        edmModel.SetAnnotationValue<ClrTypeAnnotation>(x, new ClrTypeAnnotation(clrTypeUser));
                });

                return edmModel;
            }
        }
```
After that, we will try to execute the same request.
![image](https://github.com/OData/AspNetCoreOData/assets/57600027/d0b25591-e8bd-4c2e-8717-b2f74b650d01)
![image](https://github.com/OData/AspNetCoreOData/assets/57600027/f3472011-7e52-4e8b-aa93-42b624ef32c6)

We can see that the parameters were not passed and we received the response "No content".

In edmModel.SchemaElements. we have information about actions.
Perhaps we need to register something additionally?
![image](https://github.com/OData/AspNetCoreOData/assets/57600027/da1803e0-be5f-44fb-9344-1fbc2bfcbd63)

All other functionality like $select , $expand etc works

**Comment by xuzhg** [comment]
@ipr9n It works at first it seems the 'reading' is no going to odata deserialization.  Because OData action only accepts 'ODataActionParameters' as the parameter in the controller/action. So, `[FromBody]Book book ` seems using JSON deserializer.

After reading the model, it can't work. I don't know the reason from your screen snapshop. If you can share your repo link, i can take a look for you.
Of course, can you share the model binder error message for me ahead?  You can debug on the beginning of the action and looking the 'ModelState' property from the controller (or this). It contains the errors. Thanks.

**Comment by ipr9n** [comment]
@xuzhg 
At the moment there is no repository for this project, but the same situation happens when OdataActionParameters are used.

The complete code for this project includes two controllers (the code in my first post), two models, and a startup class.
I can upload the full solution if that makes it easier. 

I tried [FromBody], because starting from version 8.0.10 it became possible
![image](https://github.com/OData/AspNetCoreOData/assets/57600027/29505124-34af-4935-8ae7-90ea8779aeaf)

Thank you in advance.

**Comment by ipr9n** [comment]
I seem to have found a solution. 
After researching the odata, I realized that when reading from a file, NavigationSource for Actions is lost.
EntitySet in OdataPath segment was not mapped.
I found what method is used when constructing the ODataPath for actions.
![image](https://github.com/OData/AspNetCoreOData/assets/57600027/8bf9eb40-8416-41fa-87ed-298f528c853b)
And the solution, after which everything seems to work, is to add "mapping" between the entity set and the action
`edmModel.SetAnnotationValue<ReturnedEntitySetAnnotation>(x, new ReturnedEntitySetAnnotation("Books"));`
