### ISSUE TITLE
Using $compute with ODataQueryOptions<T> not supported?

### ISSUE THREAD

**Issue by blueghostuk** [OData/AspNetCoreOData#921]
### Discussed in https://github.com/OData/AspNetCoreOData/discussions/920

<div type='discussions-op-text'>

<sup>Originally posted by **blueghostuk** May 15, 2023</sup>
$compute does not seem to work when using `ODataQueryOptions<T>`.  A simple example calculating the length of a string and selecting it.

We are using EF Core, if I just pass $compute and $select, it fails with an error like:

`Microsoft.OData.ODataException: Could not find a property named '{{propertyName}}' on type '{{entityType}}'.`

If I also pass a $filter, I can see the SQL being generated but then fails with:
`System.InvalidOperationException: Sequence contains no matching element
         at System.Linq.ThrowHelper.ThrowNoMatchException()
         at Microsoft.AspNetCore.OData.Query.Container.JsonPropertyNameMapper.MapProperty(String propertyName)
         at Microsoft.AspNetCore.OData.Query.Container.NamedProperty`1.ToDictionaryCore(Dictionary`2 dictionary, IPropertyMapper propertyMapper, Boolean includeAutoSelected)
         at Microsoft.AspNetCore.OData.Query.Wrapper.SelectExpandWrapper.ToDictionary(Func`3 mapperProvider)
         at Microsoft.AspNetCore.OData.Query.Wrapper.SelectSomeConverter`1.Write(Utf8JsonWriter writer, SelectSome`1 value, JsonSerializerOptions options)`

Example project here - https://github.com/blueghostuk/odata-compute-issue

Is there anything I am doing wrong? Or is this not supported?

</div>

**Comment by xuzhg** [comment]
@blueghostuk Please take a look the fix at: #928. Thanks.

**Comment by blueghostuk** [comment]
Thanks for the quick fix!
